README.md
在构建完 `ipython/notebook` 的容器后,运行会报:
```
exec: "docker-entrypoint.sh": executable file not found in $PATH
```
经检查是脚本未添加可执行权限所致
=> 修复容器运行时找不到可执行文件的错误

pages/20.python-docker/03.python-docker-002/docs.md
=> fix spell from 'php' to 'python'

scripts/lsync.sh
增加一个脚本，比对 en 和 zh 之间的不同，使用方法为：
In the repo directory, run 
```
./scripts/lsync.sh docs/en/
```
to check differences between en and zh.
=> add a script to find changes between en and zh

docs/en/docs/install/commercial/clusterconfig.md, docs/en/docs/install/community/k8s/offline.md, docs/en/docs/install/community/k8s/online.md, docs/en/docs/install/install-dce-community.md, docs/en/docs/install/offline-intall-community.md, docs/zh/docs/install/community/k8s/offline.md, docs/zh/docs/install/community/k8s/online.md
update apiVersion to `provision.dao…cloud.io/v1alpha3`
```bash
root@k3sdce5:~# ./dce5-installer install-app -c clusterConfig.yaml -z
[Error]:[Error] invalid ClusterConfig: invalid apiVersion: provision.daocloud.io/v1alpha2, only support provision.daocloud.io/v1alpha3
root@k3sdce5:~# cat clusterConfig.yaml
apiVersion: provision.daocloud.io/v1alpha2
kind: ClusterConfig
spec:
loadBalancer:
type: metallb
istioGatewayVip: 10.211.55.232/32 #
insightVip: 10.211.55.231/32      #
```
=> dce5-installer: update clusterConfig.yaml

docs/zh/docs/install/intro.md
fix deploy  url 404
"https://docs.daocloud.io/install/commercial/commercial/deploy-requirements/" to 
"https://docs.daocloud.io/install/commercial/deploy-requirements/"
=> fix-commercial-deploy-requirements-url

docs/zh/docs/mspider/user-guide/security/authorize.md, docs/zh/docs/mspider/user-guide/security/params.md, docs/zh/docs/mspider/user-guide/security/peer.md
=> update mspider security params

docs/en/docs/download/modules/kpanda.md, docs/zh/docs/download/modules/kpanda.md
- Fix typo
- Remove `0.20.0+dev-2f4f4368` link to download since its checksum is incorrect and the suffix `+dev-2f4f4368` indicates it is not a officially released version
=> update kpanda download page

docs/en/docs/install/commercial/prepare.md, docs/en/docs/install/install-tools.md, docs/zh/docs/install/commercial/prepare.md, docs/zh/docs/install/install-tools.md
In the original document of installing DCE5 Commercial,  the version of install_prerequisite is v0.8.0, but the dependent offline package isv0.9.0.  To avoid ambiguity and update to the latest installer version, we make the PR.
=> update the latest installer version and avoid ambiguity

docs/en/mkdocs.yml, docs/zh/mkdocs.yml
优化文档结尾 `/` 的使用问题，根据 Issue #1876 提出的问题分析，
这是因为 `mkdocs` 在处理 md>html 时，如果在路径 `xxx` 之后加上 `/` 无法判断时会跳转到失败页面，一般依赖文件夹下有 index.md 或者 readme.md
```yaml
use_directory_urls: false # disbale https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
```
use_directory_urls 是在构建文件时是否已目录为结尾，默认是启用，本次 PR 的目的是关闭此配置
效果如下：
Source file | use_directory_urls: true | use_directory_urls: false
-- | -- | --
index.md | / | /index.html
api-guide.md | /api-guide/ | /api-guide.html
about/license.md | /about/license/ | /about/license.html
在现有文档站中
```yaml
- Old: https://docs.daocloud.io/install/install-tools/  #隐含了 index.html
- New: https://docs.daocloud.io/install/install-tools.html
```
此次升级不会导致原路径失效，但会优化文档站内部路由；且 **可有效解决使用 CDN 缓存导致的网页内容更新不及时问题**
=> Fix the issue with the document's ending suffix '/'.

docs/en/docs/community/index.md
Remove links here and remain text only.
=> Fix links in community index

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/rabbitmq.md
download: rabbitmq version updated to v0.13.1
=> download: rabbitmq version updated to v0.13.1

docs/en/docs/insight/quickstart/install/offline-install.md, docs/zh/docs/insight/quickstart/install/offline-install.md
update: docs/zh/docs/insight/quickstart/install/offline-install.md
In load-image.yaml, .target. containerRepository is not needed any more.
=> update offline install to remove containerRepository

docs/en/docs/mspider/user-guide/service-list/out-to-in.md, docs/en/docs/mspider/user-guide/service-mesh/capacity-resources.md, docs/zh/docs/mspider/user-guide/service-list/out-to-in.md, docs/zh/docs/mspider/user-guide/service-mesh/capacity-resources.md
=> fix mspider typos

docs/en/docs/community/index.md, docs/en/docs/community/kasmcloud.md, docs/en/docs/community/kube-node-tuning.md, docs/en/docs/community/piraeus.md, docs/en/navigation.yml, docs/zh/docs/community/index.md, docs/zh/docs/community/kasmcloud.md, docs/zh/docs/community/kube-node-tuning.md, docs/zh/docs/community/piraeus.md, docs/zh/navigation.yml
Add 3 projects:
- piraeus
- kasmcloud
- kube-node-tunning
与 DaoCloud 组织的 README 保持一致
=> Add 3 eco projects in community/

docs/en/docs/kant/user-guide/node/access-guide.md, docs/en/docs/kant/user-guide/node/create-access-guide.md, docs/en/docs/kant/user-guide/node/index.md, docs/en/navigation.yml, docs/zh/docs/kant/user-guide/node/access-guide.md, docs/zh/docs/kant/user-guide/node/create-access-guide.md
=> [en] Add access-guide docs to kant

docs/zh/docs/install/community/k8s/offline.md, docs/zh/docs/install/community/k8s/online.md, docs/zh/docs/install/install-tools.md
Related to https://github.com/DaoCloud/DaoCloud-docs/discussions/1241#discussioncomment-10258123
这 2 个页面确实过于相似，要设法优化一下了。本 PR 仅作抛砖引玉，先改了少量文字：
- [在线安装到 K8s 集群](https://docs.daocloud.io/install/community/k8s/online/#_1)
- [离线安装到 K8s 集群](https://docs.daocloud.io/install/community/k8s/offline/#_1)
几个问题：
- 离线安装有 公有云、非公有云之分吗？
- 要说清楚 在线下载 -> 离线安装 的切换过程
cc @samzong 
See preview: 
https://deploy-preview-5201--daocloud-docs.netlify.app/install/community/k8s/offline
=> Discuss and fix some offline description

docs/en/docs/kant/user-guide/node/container-engine-install.md, docs/en/navigation.yml, docs/zh/docs/kant/user-guide/node/container-engine-install.md
=> [en]: add container-engine-install in kant/user-guide

docs/zh/docs/amamba/user-guide/pipeline/retain-jenkins-config.md, docs/zh/navigation.yml
See preview:
https://deploy-preview-5965--daocloud-docs.netlify.app/amamba/user-guide/pipeline/retain-jenkins-config
=> add retain jenkins config docs

docs/zh/docs/amamba/components-grafana-dashboard.md, docs/zh/navigation.yml
See preview:
https://deploy-preview-5966--daocloud-docs.netlify.app/amamba/components-grafana-dashboard
=> add amamba components dashboard

docs/zh/docs/middleware/mysql/faq/mgr-troubleshooting.md
=> added a method to handle pods that are always in terminating state

docs/zh/docs/install/commercial/start-install.md, docs/zh/docs/install/community/k8s/k8s-dce-deploy.md, docs/zh/docs/install/community/k8s/offline.md, docs/zh/docs/install/community/k8s/online.md, docs/zh/docs/install/community/kind/online.md
还缺这一节的离线包：
```markdown
=== "V0.24.0"
| 操作系统版本 | 点击下载 |
| :--------- | :------ |
| CentOS 7     | [os-pkgs-centos7-v0.21.1.tar.gz](https://files.m.daocloud.io/github.com/kubean-io/kubean/releases/download/v0.21.1/os-pkgs-centos7-v0.21.1.tar.gz) |
| Redhat 8     | [os-pkgs-redhat8-v0.21.1.tar.gz](https://files.m.daocloud.io/github.com/kubean-io/kubean/releases/download/v0.21.1/os-pkgs-redhat8-v0.21.1.tar.gz) |
| Redhat 7     | [os-pkgs-redhat7-v0.21.1.tar.gz](https://files.m.daocloud.io/github.com/kubean-io/kubean/releases/download/v0.21.1/os-pkgs-redhat7-v0.21.1.tar.gz) |
| Redhat 9     | [os-pkgs-redhat9-v0.21.1.tar.gz](https://files.m.daocloud.io/github.com/kubean-io/kubean/releases/download/v0.21.1/os-pkgs-redhat9-v0.21.1.tar.gz) |
| Ubuntu 20.04  | …
```
=> update install to v0.25.0

docs/zh/navigation.yml
Revert the nav changes in #6217, since the top and left nav disappear:
https://docs.daocloud.io/download/
=> Add back download-section in nav
