docs/en/docs/amamba/offline-upgrade.md
docs/zh/docs/amamba/offline-upgrade.md

update amamba offline-upgrade.md

---

docs/zh/docs/install/commercial/start-install.md

fix-Addon Offline Packages discribe

---

docs/en/docs/mspider/images/architecture1.svg
docs/en/docs/mspider/intro/comp-archi-ui/architect.md
docs/zh/docs/mspider/images/architecture1.svg
docs/zh/docs/mspider/intro/comp-archi-ui/architect.md

update comp-archi-ui/architect.md for mspider

---

docs/en/docs/mspider/user-guide/service-list/out-to-in.md

fix mspider typos

---

docs/en/docs/mspider/user-guide/service-mesh/capacity-resources.md
docs/zh/docs/mspider/user-guide/service-mesh/capacity-resources.md

update mspider capacity

---

docs/en/docs/kant/user-guide/edge-network/deploy-edgemesh.md
docs/zh/docs/kant/user-guide/edge-network/deploy-edgemesh.md

fix kant YAML

---

docs/zh/docs/virtnest/vm/index.md

virtnest-fix/3335

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.15.1.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.15.1.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.15.1

download: dce5 version updated to v0.15.1

---

docs/en/docs/download/business/dce5-installer-history.md
docs/en/docs/download/business/dce5-installer-v0.15.1.md
docs/en/docs/download/free/dce5-installer-history.md
docs/en/docs/download/free/dce5-installer-v0.15.1.md
docs/en/docs/download/index.md
docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.15.1.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.15.1.md

[en] Update download to installer 0.15.1

---

docs/en/docs/kant/user-guide/node/manage-node.md
docs/en/docs/kant/user-guide/node/managed-node.md
docs/en/navigation.yml
docs/zh/navigation.yml

fix kant navigation

---

docs/zh/docs/virtnest/install/index.md

virtnest-fix3376

---

docs/en/docs/mspider/intro/index.md
docs/zh/docs/mspider/intro/index.md

Update mspider index

---

docs/zh/docs/ghippo/install/reverse-proxy.md

fix reverse proxy documentation

---

docs/zh/docs/kpanda/best-practice/add-master-node.md

解决如下问题：
https://gitlab.daocloud.cn/ndx/engineering/kpanda/-/issues/3832

update add master node

---

docs/zh/docs/kpanda/best-practice/add-master-node.md

update user guide of add master node

---

docs/en/docs/kpanda/best-practice/add-master-node.md
docs/zh/docs/kpanda/best-practice/add-master-node.md

update a best practice: add-master-node.md in kpanda

---

docs/en/docs/amamba/user-guide/pipeline/pipeline-syntax.md
docs/zh/docs/amamba/user-guide/pipeline/pipeline-syntax.md

[en] update amamba: pipeline-syntax.md

---

docs/en/docs/kpanda/user-guide/gpu/nvidia/mig/create_mig.md
docs/zh/docs/kpanda/user-guide/gpu/nvidia/mig/create_mig.md

[en] Sync gpu/nvidia/mig/create_mig.md

---

docs/zh/docs/kpanda/user-guide/clusters/cluster-scheduler-plugin.md

update cluster-scheduler-plugin.md for kpanda-clusters

---

docs/en/docs/skoala/best-practice/gateway02.md

Remove zh images from en/skoala/best-practice/gateway02.md

---

docs/en/docs/install/upgrade.md
docs/zh/docs/install/upgrade.md

Add --upgrade options to install/upgrade.md

---

scripts/docs/gen_word_pdf.md

doc: add gen_word_pdf.md

---

docs/en/docs/dce/index.md
docs/en/docs/trial/index.md
docs/zh/docs/dce/index.md
docs/zh/docs/trial/index.md

Add icons and color to trial/index.md

---

docs/zh/docs/baize/intro/install.md

doc: baize update install doc

---

docs/en/docs/baize/best-practice/deploy-nfs-in-worker.md
docs/en/docs/baize/intro/install.md
docs/en/navigation.yml
docs/zh/docs/baize/intro/install.md

[en] Sync baize best practice and install docs

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.15.2.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.15.2.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.15.2

download: dce5 version updated to v0.15.2

---

docs/en/docs/skoala/cloud-ms/index.md
docs/en/docs/skoala/cloud-ms/lane.md
docs/en/navigation.yml

Add this en page after zh #4041

[en] Add traffic lane desc to skoala

---

docs/en/docs/virtnest/vm/index.md
docs/en/docs/virtnest/vm/vm-network.md
docs/en/docs/virtnest/vm/vm-sc.md
docs/en/docs/virtnest/vm/vm-windows.md
docs/en/navigation.yml
docs/zh/docs/virtnest/vm/index.md
docs/zh/docs/virtnest/vm/vm-windows.md

[en] Update virtnest/vm docs

---

docs/en/docs/insight/best-practice/tail-based-sampling.md
docs/en/navigation.yml

[en] Add an insight best practice: tail-based-sampling.md

---

docs/en/docs/install/os-install/TencentOS-install-dce5.0.md
docs/en/docs/install/os-install/oracleLinux-install-dce5.0.md
docs/en/docs/install/os-install/otherlinux.md
docs/en/docs/install/os-install/uos-v20-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/en/docs/skoala/quickstart/skoala.md
docs/zh/docs/install/os-install/TencentOS-install-dce5.0.md
docs/zh/docs/install/os-install/oracleLinux-install-dce5.0.md
docs/zh/docs/install/os-install/otherlinux.md
docs/zh/docs/install/os-install/uos-v20-install-dce5.0.md
docs/zh/docs/install/release-notes.md

Fix #4023 
- 修复中英文档中的拼写 manifest

Replace mainfest with manifest

---

docs/en/docs/kairship/intro/offline-upgrade.md
docs/en/docs/kpanda/intro/offline-upgrade.md
docs/en/docs/kpanda/user-guide/backup/offline-upgrade.md
docs/en/docs/kpanda/user-guide/security/offline-upgrade-dowl.md
docs/zh/docs/kairship/intro/offline-upgrade.md
docs/zh/docs/kant/intro/offline-upgrade.md
docs/zh/docs/kpanda/intro/offline-upgrade.md
docs/zh/docs/kpanda/user-guide/backup/offline-upgrade.md
docs/zh/docs/kpanda/user-guide/inspect/offline-upgrade.md
docs/zh/docs/kpanda/user-guide/security/offline-upgrade-dowl.md

Update annotations about .tar.gz path

---

docs/zh/docs/kant/user-guide/edge-unit/create-internal-unit.md

创建边缘单元新增修改 KubeEdge 和 Kant 镜像仓库默认值 描述

update creat edge unit

---

docs/en/docs/kpanda/user-guide/scale/knative/knative.md
docs/en/docs/kpanda/user-guide/scale/knative/playground.md
docs/en/docs/kpanda/user-guide/scale/knative/sense.md
docs/en/navigation.yml
docs/zh/docs/kpanda/user-guide/scale/knative/knative.md
docs/zh/docs/kpanda/user-guide/scale/knative/playground.md

update knative docs

---

docs/en/docs/kant/user-guide/edge-unit/create-internal-unit.md

[en] Update create-internal-unit.md for kant

---

docs/en/docs/insight/quickstart/install/upgrade-note.md
docs/zh/docs/insight/quickstart/install/upgrade-note.md

update insight: upgrade-note.md

---

docs/en/docs/kangaroo/best-practice/lb.md
docs/en/navigation.yml
docs/zh/docs/kangaroo/best-practice/lb.md

update kangaroo: best-practice/lb.md

---

docs/en/docs/kant/intro/concepts.md
docs/en/docs/kant/user-guide/edge-network/deploy-edgemesh.md
docs/en/docs/kant/user-guide/edge-network/index.md
docs/en/docs/kant/user-guide/route/index.md
docs/en/navigation.yml

Fix typos in kant

---

docs/en/docs/kpanda/user-guide/clusters/cluster-scheduler-plugin.md
docs/en/navigation.yml
docs/zh/docs/kpanda/user-guide/clusters/cluster-scheduler-plugin.md

Fix #3965 
Fix #3966 
Fix #3967 
Fix #3975
Fix #3977 
Fix #3978
Fix #3979 
Fix #3980
Fix #3981 
Fix #3982

[en] Add cluster-scheduler-plugin.md to kpanda

---

docs/en/docs/kpanda/user-guide/gpu/volcano_user_guide.md
docs/en/navigation.yml
docs/zh/navigation.yml

[en] Add gpu/volcano_user_guide.md

---

docs/zh/docs/mspider/intro/release-notes.md

docs: update release note

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.16.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.16.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.16.0

download: dce5 version updated to v0.16.0

---

docs/en/navigation.yml
docs/zh/navigation.yml

Follow k8s/blog: https://kubernetes.io/blog/

remove date from blog nav

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.16.1.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.16.1.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.16.1

download: dce5 version updated to v0.16.1

---

docs/zh/navigation.yml

update nav for egress

---

docs/en/docs/install/air-tag-download.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/k8s-install/ecs-install-dce5.0.md
docs/en/docs/install/k8s-install/ocp-install-dce5.0.md
docs/en/docs/install/os-install/TencentOS-install-dce5.0.md
docs/en/docs/install/os-install/oracleLinux-install-dce5.0.md
docs/en/docs/install/os-install/uos-v20-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/zh/docs/install/k8s-install/ocp-install-dce5.0.md

[en] update installer to v0.16.1

---

docs/en/docs/insight/quickstart/install/offline-install.md
docs/zh/docs/insight/quickstart/install/offline-install.md

insight: update insight offline upgrade doc

---

docs/zh/docs/baize/developer/notebooks/notebook-with-ssh.md
docs/zh/navigation.yml

docs: baize add ssh remote access Notebook

---

docs/en/docs/ghippo/user-guide/audit/open-audit.md
docs/en/docs/install/best-practices/thinder-restore.md
docs/en/docs/network/modules/metallb/source_ip.md
docs/zh/docs/ghippo/user-guide/audit/open-audit.md
docs/zh/docs/install/best-practices/thinder-restore.md
docs/zh/docs/network/modules/metallb/source_ip.md

fix typo about clusterConfig.yaml

---

docs/en/docs/kant/user-guide/node/index.md
docs/zh/docs/kant/user-guide/node/index.md

fix mermaid for kant/user-guide/node

---

docs/en/docs/network/modules/spiderpool/index.md
docs/zh/docs/network/modules/spiderpool/index.md

docs: update spiderpool index.md

docs: update spiderpool index.md

---

docs/en/docs/network/modules/spiderpool/install/install.md
docs/zh/docs/network/modules/spiderpool/install/install.md

docs: Optimize spiderpool installation docs

docs: Optimize spiderpool installation docs

---

docs/zh/docs/kpanda/user-guide/clusters/create-cluster.md

kpanda update create cluster

---

docs/zh/docs/kpanda/best-practice/add-master-node.md
docs/zh/docs/kpanda/best-practice/create-ubuntu-on-centos-platform.md
docs/zh/docs/kpanda/best-practice/dce4-5-migration.md
docs/zh/docs/kpanda/best-practice/etcd-backup.md
docs/zh/docs/kpanda/best-practice/kubean-low-version.md
docs/zh/docs/kpanda/user-guide/configmaps-secrets/use-configmap.md
docs/zh/docs/kpanda/user-guide/configmaps-secrets/use-secret.md

update code annotations in kpanda best-practice

---

docs/en/docs/ghippo/user-guide/personal-center/ssh-key.md
docs/en/navigation.yml
docs/zh/docs/ghippo/user-guide/personal-center/ssh-key.md

[en] Add personal-center/ssh-key.md to ghippo

---

docs/zh/docs/insight/intro/index.md
docs/zh/docs/insight/quickstart/res-plan/index.md
docs/zh/navigation.yml

1. 调整侧边栏内容
2. 调整 Insight Intro 页
3. 增加 ”容量规划“ 模块首页

polish nav & update intro

---

docs/zh/docs/mspider/intro/sla.md
docs/zh/navigation.yml

docs: mspider add sla

---

docs/zh/docs/kant/best-practice/develop-device-mapper.md
docs/zh/docs/kant/best-practice/device-control.md
docs/zh/navigation.yml

[kant] Update best practices and nav

---

docs/en/docs/ghippo/user-guide/audit/gproduct-audit/insight.md
docs/zh/docs/ghippo/user-guide/audit/gproduct-audit/insight.md

audit: update insight audit

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.17.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.17.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.17.0

download: dce5 version updated to v0.17.0

---

docs/en/docs/dce/dce-rn/20240330.md
docs/zh/docs/dce/dce-rn/20240330.md
docs/zh/docs/dce/dce-rn/20240430.md
docs/zh/navigation.yml

See preview: https://deploy-preview-4352--daocloud-docs.netlify.app/dce/dce-rn/20240430

Add dce-20240430 release notes

---

docs/en/docs/install/air-tag-download.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/install-tools.md
docs/en/docs/install/os-install/TencentOS-install-dce5.0.md
docs/en/docs/install/os-install/neokylin-install-dce5.0.md
docs/en/docs/install/os-install/oracleLinux-install-dce5.0.md
docs/en/docs/install/os-install/otherlinux.md
docs/en/docs/install/os-install/uos-v20-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/en/docs/install/upgrade.md
docs/en/navigation.yml
docs/zh/docs/install/install-tools.md
docs/zh/docs/install/os-install/neokylin-install-dce5.0.md

[en] Update installer pages to v0.17.0

---

docs/zh/docs/network/intro/releasenotes.md

update spidernet releasenotes

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.17.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.17.0

download: addon version updated to v0.17.0

---

docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/release-notes.md

[en] Fix version typo for commercial install

---

docs/en/docs/community/icons/index.md
docs/zh/docs/community/icons/index.md

KubeSphere and Kubernetes are the opposite positions, correct them.

Update community icons index.md

---

docs/zh/docs/kpanda/user-guide/clusters/k8s-cert-management.md
docs/zh/navigation.yml

kpanda add user guide certmgmt

---

docs/en/docs/amamba/user-guide/tools/integrated-toolchain.md
docs/zh/docs/amamba/user-guide/tools/integrated-toolchain.md

[en] update tools/integrated-toolchain.md

---

docs/en/navigation.yml

fix: Spiderpool installation jump in English mode failed.

---

docs/en/docs/network/modules/spiderpool/upgrade.md
docs/zh/docs/network/modules/spiderpool/upgrade.md

fix: optimizate upgrade docs

---

docs/zh/docs/virtnest/import/import-ubuntu.md
docs/zh/navigation.yml

fix https://github.com/DaoCloud/DaoCloud-docs/discussions/4424

Update import-ubuntu.md for virtnest

---

docs/en/docs/kpanda/best-practice/multi-arch.md

【en】Sync multi-arch.md

---

docs/en/docs/amamba/offline-upgrade.md
docs/en/docs/amamba/user-guide/gitops/gitops-secret.md
docs/en/navigation.yml
docs/zh/docs/amamba/offline-upgrade.md
docs/zh/docs/amamba/user-guide/gitops/gitops-secret.md
docs/zh/navigation.yml

[en] update nav and add gitops-secret.md

---

docs/zh/docs/download/modules/vgpu.md

add 10 more drivers to download/vgu

---

docs/en/docs/ghippo/user-guide/workspace/folder-permission.md
docs/zh/docs/ghippo/user-guide/workspace/folder-permission.md

adjust the tables in folder-permission

---

docs/en/docs/virtnest/vm/auto-migrate.md
docs/en/navigation.yml
docs/zh/docs/virtnest/vm/auto-migrate.md

[en] add vm/auto-migrate.md

---

docs/en/docs/kpanda/user-guide/clusters/access-cluster.md
docs/en/docs/kpanda/user-guide/clusters/cluster-scheduler-plugin.md
docs/zh/docs/kpanda/user-guide/clusters/cluster-scheduler-plugin.md

[en] update cluster-scheduler-plugin

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.18.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.18.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.18.0

download: dce5 version updated to v0.18.0

---

docs/en/docs/amamba/intro/index.md
docs/zh/docs/amamba/intro/index.md

fix a bug in amamba-intro, upgrade [en]version

---

docs/zh/docs/insight/faq/expand-once-es-full.md
docs/zh/navigation.yml

add a faq: expand-once-es-full.md

---

docs/en/docs/kairship/workload/yaml.md
docs/zh/docs/kairship/workload/yaml.md

fix a bug in kairship-workloads

---

docs/en/docs/kpanda/user-guide/gpu/volcano/volcano-gang-scheduler.md
docs/zh/docs/kpanda/user-guide/gpu/volcano/volcano-gang-scheduler.md

fix a bug in volcano-gang-scheduler

---

docs/zh/docs/kpanda/best-practice/kubean-low-version.md

Mentioned in  #4600 
See preview: https://deploy-preview-4601--daocloud-docs.netlify.app/kpanda/best-practice/kubean-low-version

have a try to improve seo and search hits

---

docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/zh/docs/install/community/k8s/k8s-dce-deploy.md

add a description in k8s-dce-deploy

---

docs/en/navigation.yml
docs/zh/navigation.yml

Update the best practice entry name

---

docs/zh/docs/baize/developer/notebooks/baizectl.md
docs/zh/navigation.yml

Add user guide of baizectl

---

docs/en/docs/kpanda/user-guide/scale/custom-hpa.md
docs/zh/docs/kpanda/user-guide/scale/custom-hpa.md

Fix a prerequisite in custom-hpa.md

---

docs/en/docs/network/intro/issues.md
docs/en/navigation.yml
docs/zh/docs/network/intro/issues.md
docs/zh/navigation.yml

Update after #4626 
See preview: https://deploy-preview-4643--daocloud-docs.netlify.app/network/intro/issues

optimize the structure of network/intro/issues.md

---

docs/en/docs/install/commercial/start-install.md

[en] update commercial/start-install.md

---

docs/en/navigation.yml
docs/zh/navigation.yml

update nav for gitops

---

docs/en/docs/network/intro/issues.md
docs/zh/docs/network/intro/issues.md

Signed-off-by: lou-lan <loulan@loulan.me>

Update net issues docs

---

docs/zh/docs/baize/developer/notebooks/baizectl.md

baize: fix baizectl command tips, submit job resource configure

---

docs/zh/docs/baize/best-practice/checkpoint.md
docs/zh/navigation.yml

baize: add bp checkpoint

---

docs/zh/docs/network/intro/issues.md

not ready, don't merge.
still need to continue to supplement.

docs: Add some known issues of spiderpool

---

docs/en/docs/kpanda/user-guide/gpu/volcano/volcano_user_guide.md
docs/zh/docs/kpanda/user-guide/gpu/volcano/volcano_user_guide.md

update volcano user guide

---

docs/en/docs/kpanda/user-guide/scale/custom-hpa.md
docs/zh/docs/kpanda/user-guide/scale/custom-hpa.md

Fix yaml indentations in custom-hpa.md

---

docs/en/docs/kpanda/best-practice/multi-arch.md
docs/zh/docs/kpanda/best-practice/multi-arch.md

update package versions in kpanda/best-practice/multi-arch.md

---

docs/en/docs/install/commercial/manifest.md

[en] update install/commercial/manifest.md

---

.github/CODEOWNERS

update codeowner list

---

docs/en/docs/install/commercial/deploy-requirements.md

en: fix a unit in commercial/deploy-requirements.md

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.19.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.19.0

download: addon version updated to v0.19.0

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.19.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.19.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.19.0

download: dce5 version updated to v0.19.0

---

docs/en/docs/storage/hwameistor/install/deploy-operator.md
docs/zh/docs/storage/hwameistor/install/deploy-operator.md

update yaml in install/deploy-operator/

---

docs/en/docs/amamba/intro/release-notes.md
docs/en/docs/install/commercial/cluster-config.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/k8s-install/ecs-install-dce5.0.md
docs/en/docs/install/k8s-install/ocp-install-dce5.0.md
docs/en/docs/install/os-install/neokylin-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/en/docs/storage/hwameistor/releasenotes.md

English version of release notes has been updated to keep in line with the Chinese one.
The latest Chinese version see:
https://github.com/DaoCloud/DaoCloud-docs/pull/4764

[en]update to v0.19.0

---

docs/en/docs/kairship/intro/features.md

fix features.html#multicloud-workloads

---

docs/en/mkdocs.yml
docs/zh/mkdocs.yml

Fix bread crumb issue in en

---

docs/en/docs/videos/use-cases.md

en: fix the title in videos/use-cases/

---

docs/en/docs/middleware/redis/best-practice/cluster2sentinel.md
docs/en/navigation.yml
docs/zh/navigation.yml

Seems already fixed #2798 
This PR just adjusted the navigation bar

adjust the redis navigation-bar

---

docs/zh/docs/middleware/postgresql/user-guide/antiaffinity.md

add yaml file to postgresql-antiaffinity

---

docs/en/docs/kairship/intro/release-notes.md
docs/en/docs/virtnest/intro/release-notes.md

Update the English version to keep in line with the Chinese version.

[en]update virtnest and kairship releasenotes

---

docs/en/docs/virtnest/install/install-dependency.md
docs/zh/docs/virtnest/install/install-dependency.md

fixed #4373
Updated English version

[en]update virnest install-dependency

---

docs/zh/docs/baize/developer/notebooks/notebook-with-ssh.md

baize: upgrade ssh command example

---

docs/zh/docs/amamba/user-guide/pipeline/system-env.md
docs/zh/navigation.yml

update system env to amamba/pipeline

---

docs/en/docs/kairship/policy/override.md

[en]update kairship-policy override

---

docs/en/docs/amamba/user-guide/pipeline/cicd_vm.md
docs/en/docs/amamba/user-guide/pipeline/install-jenkins.md
docs/en/docs/amamba/user-guide/pipeline/jenkins-agent.md
docs/en/docs/amamba/user-guide/pipeline/podman.md
docs/en/docs/amamba/user-guide/pipeline/system-env.md
docs/en/navigation.yml
docs/zh/docs/amamba/user-guide/pipeline/jenkins-agent.md
docs/zh/docs/amamba/user-guide/pipeline/podman.md

[en] add pipeline pages

---

docs/en/docs/middleware/minio/user-guide/create.md
docs/zh/docs/middleware/minio/user-guide/create.md

optimize minio user-guide create

---

docs/zh/docs/insight/quickstart/install/gethosturl.md

optimize insight-install-gethosturl

---

docs/en/docs/kangaroo/intro/upgrade.md
docs/zh/docs/kangaroo/intro/upgrade.md

make code comment prettier in kangaroo/intro/upgrade.md

---

docs/en/docs/kant/best-practice/develop-device-mapper.md
docs/zh/docs/kant/best-practice/develop-device-mapper.md

Add tabs to develop-device-mapper.md for kant

---

docs/zh/docs/install/best-practices/remanage-work-cluster.md
docs/zh/navigation.yml

@Rei1010 @ErikJiang review xia

add customer-case

---

docs/en/docs/kairship/intro/architecture.md
docs/en/docs/kairship/intro/concepts.md
docs/zh/docs/kairship/intro/architecture.md

[en]update kairship-intro

---

docs/en/docs/install/best-practices/remanage-work-cluster.md
docs/en/navigation.yml
docs/zh/docs/install/best-practices/remanage-work-cluster.md

[en] Add best-practices/remanage-work-cluster.md

---

docs/en/docs/install/best-practices/all-in-one-machine.md
docs/en/docs/install/best-practices/cve-20240-21626.md
docs/en/docs/install/best-practices/etcd-host-deploy.md
docs/en/docs/install/best-practices/extend-params.md
docs/en/docs/install/best-practices/offline-clipper.md
docs/en/docs/install/commercial/cluster-config.md
docs/en/docs/install/commercial/deploy-requirements.md
docs/en/docs/install/commercial/external/external-binary.md
docs/en/docs/install/commercial/external/external-middlewares.md
docs/en/docs/install/commercial/external/external-os.md
docs/en/docs/install/commercial/manifest.md
docs/en/docs/install/commercial/scenarios.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/faq.md
docs/en/docs/install/import.md
docs/en/docs/install/index.md
docs/en/docs/install/k8s-install/ecs-install-dce5.0.md
docs/en/docs/install/os-install/neokylin-install-dce5.0.md
docs/en/docs/install/os-install/oracleLinux-install-dce5.0.md
docs/en/docs/install/os-install/otherlinux.md
docs/en/docs/install/os-install/uos-v20-install-dce5.0.md
docs/en/docs/install/release-notes.md

Fix terms in installer

---

docs/zh/docs/install/best-practices/replace-os.md
docs/zh/navigation.yml

@ErikJiang @Rei1010  麻烦 review 下

[installer] add os to replace cluster without downtime

---

docs/en/docs/storage/hwameistor/application/tidb.md
docs/en/docs/storage/solutions/longhorn.md
docs/zh/docs/storage/hwameistor/application/tidb.md
docs/zh/docs/storage/solutions/longhorn.md

fix typos about kubelet

---

docs/en/docs/install/best-practices/replace-os.md
docs/en/navigation.yml
docs/zh/docs/install/best-practices/replace-os.md

[en] Add best-practices/replace-os.md

---

docs/en/docs/insight/quickstart/install/component-scheduling.md

[en] Add install/component-scheduling.md

---

docs/en/docs/kangaroo/best-practice/capacity-planning.md
docs/en/docs/kangaroo/best-practice/harbor-nginx.md
docs/zh/docs/kangaroo/best-practice/capacity-planning.md
docs/zh/docs/kangaroo/best-practice/harbor-nginx.md

Updated MTPE versions and revise yaml

[en]update kangaroo best-practice

---

docs/en/docs/insight/quickstart/install/gethosturl.md
docs/zh/docs/insight/quickstart/install/gethosturl.md

revise descriptions in insight-install-gethosturl

---

docs/zh/docs/videos/amamba.md

try to improve amamba/video

---

docs/en/docs/middleware/common/config.md
docs/en/docs/middleware/elasticsearch/intro/offline-install.md
docs/en/docs/middleware/elasticsearch/release-notes.md
docs/en/docs/middleware/elasticsearch/user-guide/basic.md
docs/en/docs/middleware/kafka/intro/offline-install.md
docs/en/docs/middleware/kafka/user-guide/template.md
docs/en/docs/middleware/minio/intro/offline-install.md
docs/en/docs/middleware/mongodb/intro/offline-install.md
docs/en/docs/middleware/mysql/intro/features.md
docs/en/docs/middleware/mysql/intro/offline-install.md
docs/en/docs/middleware/mysql/user-guide/instancemap.md
docs/en/docs/middleware/postgresql/intro/offline-install.md
docs/en/docs/middleware/rabbitmq/intro/offline-install.md
docs/en/docs/middleware/rabbitmq/release-notes.md
docs/en/docs/middleware/redis/best-practice/cluster2cluster.md
docs/en/docs/middleware/redis/best-practice/cluster2sentinel.md
docs/en/docs/middleware/redis/best-practice/sentinel2sentinel.md
docs/en/docs/middleware/redis/intro/index.md
docs/en/docs/middleware/redis/intro/offline-install.md
docs/en/docs/middleware/rocketmq/intro/offline-install.md

Related to #4956
Fixed terms in midware.

fix terms in middleware

---

docs/en/docs/middleware/postgresql/release-notes.md
docs/en/docs/middleware/redis/release-notes.md

Related to PR #4780
Update English version.

[en]update middleware releasenotes

---

docs/zh/docs/kpanda/user-guide/gpu/FAQ.md
docs/zh/docs/kpanda/user-guide/gpu/nvidia/vgpu/hami.md
docs/zh/navigation.yml

See preview: 
- https://deploy-preview-5002--daocloud-docs.netlify.app/kpanda/user-guide/gpu/faq
- https://deploy-preview-5002--daocloud-docs.netlify.app/kpanda/user-guide/gpu/nvidia/vgpu/hami

add gpu faq

---

docs/zh/docs/videos/amamba.md

try to fix the loading failure of the video poster

try to fix amamba video page

---

docs/en/docs/kangaroo/intro/release-notes.md
docs/en/docs/kangaroo/managed/harbor-migration.md
docs/en/docs/kangaroo/managed/intro.md

[en]update kangaroo releasenotes and revise other docs

---

docs/en/docs/baize/best-practice/finetunel-llm.md
docs/en/docs/baize/best-practice/train-with-deepspeed.md
docs/en/navigation.yml
docs/zh/docs/baize/best-practice/finetunel-llm.md
docs/zh/docs/baize/best-practice/train-with-deepspeed.md

Add 2 best practices to en folder

[en] Add two best practices: finetunel-llm and train-with-deepspeed

---

docs/en/docs/kpanda/user-guide/gpu/FAQ.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/vgpu/hami.md
docs/en/navigation.yml

[en] add faq and hami to gpu folder

---

docs/en/docs/kpanda/user-guide/helm/README.md
docs/en/docs/kpanda/user-guide/helm/helm-app.md
docs/en/docs/kpanda/user-guide/helm/helm-repo.md
docs/en/docs/kpanda/user-guide/helm/upload-helm.md
docs/en/navigation.yml
docs/zh/docs/kpanda/user-guide/helm/helm-repo.md

[en] update helm pages

---

docs/en/docs/videos/amamba.md
docs/en/docs/videos/baize.md
docs/en/docs/videos/ghippo.md
docs/en/docs/videos/insight.md
docs/en/docs/videos/install.md
docs/en/docs/videos/kairship.md
docs/en/docs/videos/kangaroo.md
docs/en/docs/videos/kant.md
docs/en/docs/videos/kpanda.md
docs/en/docs/videos/mcamel.md
docs/en/docs/videos/mspider.md
docs/en/docs/videos/network.md
docs/en/docs/videos/skoala.md
docs/en/docs/videos/use-cases.md
docs/zh/docs/videos/baize.md
docs/zh/docs/videos/ghippo.md
docs/zh/docs/videos/insight.md
docs/zh/docs/videos/install.md
docs/zh/docs/videos/kairship.md
docs/zh/docs/videos/kangaroo.md
docs/zh/docs/videos/kant.md
docs/zh/docs/videos/kpanda.md
docs/zh/docs/videos/mcamel.md
docs/zh/docs/videos/mspider.md
docs/zh/docs/videos/network.md
docs/zh/docs/videos/skoala.md
docs/zh/docs/videos/use-cases.md

The posters can not be displayed on the video page. 
Try to fix this issue.

fix posters on  video pages

---

docs/en/docs/amamba/user-guide/git/git.md
docs/en/docs/amamba/user-guide/gitops/argo-cd-status.md
docs/en/docs/amamba/user-guide/pm/issue.md
docs/en/navigation.yml
docs/zh/docs/amamba/user-guide/git/git.md
docs/zh/docs/amamba/user-guide/pm/issue.md
docs/zh/navigation.yml

[en] Add git repo and issue to amamba

---

docs/zh/docs/videos/baize.md

add a video to baize

---

docs/en/docs/network/intro/issues.md
docs/zh/docs/network/intro/issues.md

[en]: update network/intro/issues.md 

---

docs/en/docs/ghippo/user-guide/workspace/workspace.md

[en] update delete ws tips

---

docs/en/docs/videos/baize.md
docs/zh/docs/videos/baize.md

update baize-video headings

---

docs/en/docs/network/config/use-ippool/usage.md

[en]: update config/use-ippool/usage

---

docs/en/docs/insight/compati-test/k8s-compatibility.md
docs/en/docs/insight/compati-test/rancher-compatibility.md

Update tables and descriptions in docs

update insight-compati-test docs

---

docs/en/docs/baize/troubleshoot/cluster-not-found.md
docs/en/docs/baize/troubleshoot/index.md
docs/en/navigation.yml
docs/zh/docs/baize/troubleshoot/cluster-not-found.md

[en] Add baize/troubleshoot/cluster-not-found.md

---

docs/en/docs/ghippo/best-practice/oem/custom-idp.md

Update en page to keep in line with Chinese and UI.

[en]: update ghippo/best-practice/oem/custom-idp.md

---

docs/en/docs/kangaroo/best-practice/insecure_registry.md
docs/en/docs/kangaroo/integrate/bind-to-ws.md
docs/en/docs/kangaroo/integrate/integrate-admin.md
docs/zh/docs/kangaroo/integrate/integrate-admin.md

Update English version to keep in line with Chinese and UI.

[en]update kangaroo docs

---

docs/en/docs/storage/hwameistor/install/upgrade.md

update a command in en page to keep in line with zh page.

[en]: update hwameistor/install/upgrade

---

.github/workflows/main.path.yml
.github/workflows/main.yml
.github/workflows/pull-request-test.yaml
constraints.txt
requirements.txt

Temporary fix for high version setuptools issue

---

docs/en/docs/storage/hwameistor/intro/admission-controller.md

Update en page to keep in line with zh page and UI
Modify English expression

[en]: update hwameistor/intro/admission-controller

---

docs/en/docs/kangaroo/best-practice/lb.md
docs/en/docs/kangaroo/integrate/integrate-ws.md
docs/en/docs/kangaroo/integrate/registry-space.md
docs/en/docs/kangaroo/integrate/sync.md
docs/en/docs/kangaroo/quickstart/push.md
docs/en/docs/kangaroo/quickstart/registry-in-one.md
docs/en/docs/kangaroo/space/reclaim.md
docs/en/docs/kangaroo/space/scan.md

Optimize English version to keep in line with Chinese UI, and add some contents

[en]update kangaroo to optimize UI

---

docs/en/docs/kpanda/user-guide/gpu/ascend/Ascend_usage.md
docs/en/docs/kpanda/user-guide/gpu/ascend/vnpu.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/install_nvidia_driver_of_operator.md
docs/zh/docs/kpanda/user-guide/gpu/ascend/ascend_usage.md
docs/zh/docs/kpanda/user-guide/gpu/nvidia/install_nvidia_driver_of_operator.md

[en] update gpu docs

---

docs/en/docs/kpanda/best-practice/multi-arch.md
docs/en/docs/kpanda/best-practice/replace-first-master-node.md
docs/zh/docs/kpanda/best-practice/multi-arch.md
docs/zh/docs/kpanda/best-practice/replace-first-master-node.md

fix yaml in two kpanda/best-practice pages

---

docs/en/docs/middleware/mysql/faq/faq-mgr-parameter.md
docs/en/navigation.yml

[en]add insight-faq-mgr-parameter doc

---

docs/zh/docs/skoala/best-practice/gateway01.md
docs/zh/docs/videos/skoala.md

add a video to skoala

---

docs/zh/docs/videos/skoala.md

update skoala video: access service with gateway

---

docs/en/docs/kangaroo/space/imagelist.md

Update English version, revise some grammatical errors

[en]update kangaroo-space-imagelist

---

docs/en/docs/download/index.md
docs/zh/docs/download/index.md

update kant version in download/index

update kant version in download/index

---

docs/en/docs/virtnest/install/install-dependency.md

update the format of English version

[en]update virtnest-install-dependency

---

docs/en/docs/install/best-practices/all-in-one-machine.md
docs/en/docs/install/commercial/deploy-requirements.md
docs/en/docs/install/commercial/download-file.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/os-install/otherlinux.md
docs/zh/docs/install/commercial/start-install.md

[en] update install pages

---

docs/en/docs/download/index.md
docs/zh/docs/download/index.md

update download index

---

docs/en/docs/virtnest/vm/snapshot.md
docs/en/docs/virtnest/vm/vm-network.md
docs/zh/docs/virtnest/vm/vm-network.md

keep in line with the Chinese version

[en]update virtnest-vm docs

---

docs/zh/docs/videos/use-cases.md

add a video: ai-model training and inference

---

docs/en/docs/baize/best-practice/deploy-nfs-in-worker.md
docs/en/docs/baize/developer/notebooks/baizectl.md
docs/en/navigation.yml
docs/zh/docs/baize/best-practice/deploy-nfs-in-worker.md

- 修复中文格式
- 新增英文页面
see preview: https://deploy-preview-5156--daocloud-docs.netlify.app/en/baize/developer/notebooks/baizectl#using-specific-workspaces

[en] Add baizectl and update deploy-nfs-in-worker

---

docs/en/docs/network/modules/metallb/index.md
docs/zh/docs/network/modules/metallb/index.md

update en version to keep with zh version
optimize zh version

[en]: update modules/metallb/index

---

docs/en/docs/network/modules/metallb/usage.md
docs/zh/docs/network/modules/metallb/usage.md

update en version to keep with zh version

[en]: update modules/metallb/usage

---

docs/en/docs/network/modules/multus-underlay/dpdk.md
docs/zh/docs/network/modules/multus-underlay/dpdk.md

update en page to keep with zh page
optimize zh page

[en]: update multus-underlay/dpdk

---

docs/en/docs/amamba/quickstart/argo-karmada.md
docs/en/navigation.yml
docs/zh/docs/amamba/quickstart/argo-karmada.md
docs/zh/navigation.yml

[en] Add quickstart/argo-karmada.md

---

docs/en/docs/network/performance/cni-performance.md
docs/zh/docs/network/performance/cni-performance.md

update en version to keep in line with zh version
optimize zh page

[en]: update performance/cni-performance.md

---

docs/en/docs/baize/best-practice/add-scheduler.md
docs/en/docs/baize/developer/inference/create.md
docs/en/docs/baize/developer/inference/vllm-inference.md
docs/en/docs/baize/developer/jobs/pytorch.md
docs/en/docs/baize/developer/jobs/tensorboard.md
docs/en/docs/baize/developer/jobs/tensorflow.md
docs/en/docs/baize/developer/notebooks/baizectl.md
docs/en/docs/baize/developer/quick-start.md
docs/en/docs/baize/troubleshoot/notebook-not-controlled-by-quotas.md

[en] Fix style issues in baize/developer

---

docs/en/docs/network/modules/egressgateway/create-egpolicy.md
docs/zh/docs/network/modules/egressgateway/create-egpolicy.md

[en]: update egressgateway/create-egpolicy

---

docs/en/docs/ghippo/user-guide/platform-setting/about.md

update en page to keep in line with zh page and UI

[en]: update platform-setting/about

---

docs/en/docs/ghippo/user-guide/audit/open-k8s-audit.md
docs/zh/docs/ghippo/user-guide/audit/open-k8s-audit.md

update and optimize en version to keep in line with zh version and UI

[en]: update user-guide/audit/open-k8s-audit

---

docs/zh/docs/dce/dce-rn/20240730.md
docs/zh/navigation.yml

add dce-rn/20240730.md

---

docs/en/docs/dce/dce-rn/20231031.md
docs/en/docs/dce/dce-rn/20231231.md
docs/en/docs/dce/dce-rn/20240130.md
docs/en/docs/dce/dce-rn/20240330.md
docs/en/docs/dce/dce-rn/20240430.md
docs/en/docs/dce/dce-rn/20240530.md
docs/en/docs/dce/dce-rn/20240630.md
docs/en/docs/dce/dce-rn/20240730.md
docs/en/navigation.yml

增加英文版 dce-20240730 release notes

[en] add dce-rn/20240730.md

---

docs/zh/docs/videos/baize.md

Add a video: baize 0.7.0 what's new

---

docs/zh/docs/insight/intro/releasenote.md

fix style issues in insight release notes

---

docs/en/docs/network/modules/egressgateway/create_eg.md
docs/zh/docs/network/modules/egressgateway/create_eg.md

- Update  and optimize en version to keep in line with zh version
- Optimize zh page

[en]: update egressgateway/create_eg

---

docs/en/docs/ghippo/install/user-isolation.md

[en]: fix install/user-isolation

---

docs/en/docs/ghippo/user-guide/access-control/idprovider.md
docs/zh/docs/ghippo/user-guide/access-control/idprovider.md

fix user-guide/access-control/idprovider.md

---

docs/en/docs/insight/intro/releasenote.md

Update the English version to keep in line with the Chinese one
Sync with zh #5213

[en]update insight releasenote

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.20.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.20.0

download: addon version updated to v0.20.0

---

docs/zh/docs/download/index.md

fix addon index

---

docs/en/docs/network/modules/multus-underlay/macvlan.md
docs/zh/docs/network/modules/multus-underlay/macvlan.md

- update en page to keep in line with zh page
- optimize en/zh version

[en]: update modules/multus-underlay/macvlan

---

docs/en/docs/network/modules/multus-underlay/index.md
docs/zh/docs/network/modules/multus-underlay/index.md

Update en version to keep in line with zh version

[en]: update modules/multus-underlay/index

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.20.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.20.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.20.0

download: dce5 version updated to v0.20.0

---

docs/en/docs/install/community/kind/online.md
docs/zh/docs/install/community/kind/online.md

fix community/kind/online

---

docs/en/docs/network/config/use-ippool/cutomizedusage.md
docs/zh/docs/network/config/use-ippool/cutomizedusage.md

update en version to keep in line with zh version and UI

[en]: update config/use-ippool/cutomizedusage

---

docs/en/docs/storage/hwameistor/releasenotes.md

Update en version to keep in line with zh version

[en]: update hwameistor/releasenotes

---

docs/en/docs/network/modules/cilium/cilium-speedup.md
docs/zh/docs/network/modules/cilium/cilium-speedup.md

update en version to keep in line with zh version and UI

[en]: update modules/cilium/cilium-speedup

---

docs/en/docs/network/modules/aliyun-terway/Q_A.md
docs/zh/docs/network/modules/aliyun-terway/Q_A.md

MTPE
Optimize the Markdown format for Chinese and English page

[en]: update aliyun-terway/Q_A.md

---

docs/en/docs/ghippo/user-guide/audit/source-ip.md
docs/zh/docs/ghippo/user-guide/audit/source-ip.md

MTPE
Update en version to keep in line with zh version and UI

[en]: update user-guide/audit/source-ip.md

---

docs/en/docs/insight/intro/scenarios.md
docs/en/docs/insight/quickstart/jvm-monitor/legacy-jvm.md
docs/zh/docs/insight/quickstart/jvm-monitor/legacy-jvm.md

Updated the English version to keep in line with the Chinese one

[en]update insight docs

---

docs/zh/docs/kant/user-guide/route/create-route.md

fixed an error in zh page
fixed discussions #2753

fixed an error in user-guide/route/create-route.md

---

docs/en/docs/kairship/resource/secret.md
docs/en/docs/kairship/resource/update-configmap.md
docs/en/docs/kairship/resource/update-ingress.md

Update English version to keep in line with the Chinese page.

[en]update kairship-resource docs

---

docs/en/docs/ghippo/best-practice/oem/oem-in.md
docs/zh/docs/ghippo/best-practice/oem/oem-in.md

MTPE
Update en version to keep in line with zh version and UI

[en]: update best-practice/oem/oem-in

---

docs/en/docs/middleware/mysql/user-guide/create-mgr.md
docs/en/docs/middleware/mysql/user-guide/create.md
docs/en/docs/middleware/mysql/user-guide/logs.md

Update En version to keep in line with the Chinese version

[en] update middleware docs

---

docs/en/docs/ghippo/best-practice/navigator.md
docs/zh/docs/ghippo/best-practice/navigator.md

[en]: update best-practice/navigator.md

---

docs/en/docs/storage/solutions/helm-rook-ceph.md
docs/zh/docs/storage/solutions/helm-rook-ceph.md

fixed yaml in solutions/helm-rook-ceph

---

docs/en/docs/storage/hwameistor/intro/scheduler.md
docs/zh/docs/storage/hwameistor/intro/scheduler.md

Fix discussion #1670 in hwameistor/intro/scheduler

---

docs/en/docs/middleware/mysql/faq/faq-others.md
docs/zh/docs/middleware/mysql/faq/faq-others.md

Fixed Discussion #4888
and updated MTPE version.

Fix an discussion issue in mysql-faq and update en version

---

docs/zh/docs/install/commercial/deploy-requirements.md

fix discussion #2326 in deploy-requirements.md

---

docs/en/docs/ghippo/user-guide/personal-center/security-setting.md
docs/zh/docs/ghippo/user-guide/personal-center/security-setting.md

fix discussion #3426 in personal-center/security-setting/

---

docs/zh/docs/storage/hwameistor/resources/lvm-nodes.md

Fix hwameistor/resources/lvm-nodes in discussion #5226

---

docs/en/docs/install/uninstall.md
docs/zh/docs/install/uninstall.md

Fix part of discussion #2311 
cc @jzhupup

Fix part of discussion #2311 about uninstall commands

---

docs/en/docs/install/uninstall.md
docs/zh/docs/install/uninstall.md

Reverts DaoCloud/DaoCloud-docs#5290

Revert "Fix part of discussion #2311 about uninstall commands"

---

docs/zh/docs/download/index.md
docs/zh/docs/install/commercial/start-install.md

see preview: https://deploy-preview-5288--daocloud-docs.netlify.app/download/

Add prerequisites package to download

---

docs/en/docs/download/index.md

[en] Add prerequisites package to download

---

docs/en/docs/middleware/mysql/intro/features.md
docs/zh/docs/middleware/mysql/intro/features.md

[en] fixed a typo in middleware-mysql-features and did MTPE

---

docs/en/docs/mspider/troubleshoot/cluster-already-exist.md
docs/zh/docs/mspider/troubleshoot/cluster-already-exist.md

Fix discussion #3772 in cluster-already-exist for mspider

---

docs/en/docs/download/business/dce5-installer-v0.13.0.md
docs/en/docs/install/commercial/cluster-config.md
docs/en/docs/install/commercial/deploy-requirements.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/faq.md
docs/en/docs/install/install-tools.md
docs/en/docs/install/k8s-install/ocp-install-dce5.0.md
docs/en/docs/install/os-install/neokylin-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/en/docs/kpanda/best-practice/create-redhat9.2-on-centos-platform.md
docs/zh/docs/install/commercial/start-install.md
docs/zh/docs/install/faq.md

Update after #5198, #5234, #5288, and #5299

[en] update installer pages to v0.20.0

---

docs/en/docs/kangaroo/quickstart/admin-registry.md
docs/zh/docs/kangaroo/quickstart/admin-registry.md

Update En version to keep in line with Chinese and UI page

[en]update kangaroo-quickstart admin-registry

---

docs/en/docs/middleware/kafka/user-guide/config.md
docs/zh/docs/middleware/kafka/user-guide/config.md

Try to fix discussion #1714 
require review @justedennnnn 
THX

Fix discussion #1714 related to middleware-kafka configuration

---

docs/zh/docs/blogs/230418-karmada-failover.md

fix discussion #5190 in 230418-karmada-failover.md

---

docs/en/docs/dce/dce-rn/20231231.md
docs/en/docs/dce/dce-rn/20240730.md
docs/en/docs/kpanda/best-practice/etcd-backup.md
docs/en/docs/kpanda/best-practice/hardening-cluster.md
docs/en/docs/kpanda/intro/faq.md
docs/en/docs/kpanda/intro/offline-upgrade.md
docs/en/docs/kpanda/intro/release-notes.md
docs/en/docs/kpanda/user-guide/backup/etcd-backup.md
docs/en/docs/kpanda/user-guide/backup/offline-upgrade.md
docs/en/docs/kpanda/user-guide/clusterops/cluster-settings.md
docs/en/docs/kpanda/user-guide/gpu/Iluvatar_usage.md
docs/en/docs/kpanda/user-guide/gpu/index.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/full_gpu_userguide.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/index.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/install_nvidia_driver_of_operator.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/upgrade_yum_source_centos7_9.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/upgrade_yum_source_redhat8_4.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/vgpu/vgpu_addon.md
docs/en/docs/kpanda/user-guide/gpu/nvidia/vgpu/vgpu_user.md
docs/en/docs/kpanda/user-guide/gpu/volcano/volcano_user_guide.md
docs/en/docs/kpanda/user-guide/helm/multi-archi-helm.md
docs/en/docs/kpanda/user-guide/namespaces/exclusive.md
docs/en/docs/kpanda/user-guide/permissions/custom-kpanda-role.md
docs/en/docs/kpanda/user-guide/scale/knative/install.md
docs/en/docs/kpanda/user-guide/workloads/create-cronjob.md
docs/en/docs/kpanda/user-guide/workloads/create-daemonset.md
docs/en/docs/kpanda/user-guide/workloads/create-deployment.md
docs/en/docs/kpanda/user-guide/workloads/create-job.md
docs/en/docs/kpanda/user-guide/workloads/create-statefulset.md

Optimize en text in kpanda pages

---

docs/en/docs/amamba/intro/benefits.md
docs/en/docs/amamba/intro/index.md
docs/en/docs/amamba/intro/release-notes.md
docs/en/docs/amamba/quickstart/jenkins-custom.md
docs/en/docs/amamba/quickstart/scan-with-pipeline.md
docs/en/docs/amamba/user-guide/gitops/gitops-secret.md
docs/en/docs/amamba/user-guide/native/manage.md
docs/en/docs/amamba/user-guide/native/native-app.md
docs/en/docs/amamba/user-guide/oam/concept.md
docs/en/docs/amamba/user-guide/pipeline/credential.md
docs/en/docs/amamba/user-guide/pipeline/edit.md
docs/en/docs/amamba/user-guide/pipeline/view/view-pipeline.md
docs/en/docs/amamba/user-guide/pm/issue.md
docs/en/docs/amamba/user-guide/release/blue-green.md
docs/en/docs/amamba/user-guide/release/check-canary.md
docs/en/docs/amamba/user-guide/wizard/jar-java-app.md

[en] Update amamba release notes and fix grammar issues

---

docs/zh/docs/kant/user-guide/node/container-engine-install.md
docs/zh/docs/kant/user-guide/node/join-rqmt.md
docs/zh/navigation.yml

kant update user guide

---

docs/en/docs/kpanda/best-practice/create-ubuntu-on-centos-platform.md
docs/zh/docs/kpanda/best-practice/create-ubuntu-on-centos-platform.md

[en] update create-ubuntu-on-centos-platform.md

---

docs/en/docs/middleware/elasticsearch/release-notes.md
docs/en/docs/middleware/minio/release-notes.md
docs/en/docs/middleware/mongodb/release-notes.md
docs/en/docs/middleware/redis/release-notes.md

[en]update midware releasenotes

---

docs/en/docs/videos/index.md
docs/en/docs/videos/virtnest.md

[en]add virtnest video page

---

docs/en/navigation.yml

Add Virtnest video page to navigation

[en]add virtnest video navigation

---

docs/en/docs/kpanda/user-guide/nodes/taints.md
docs/zh/docs/kpanda/user-guide/nodes/taints.md

Fix #5247 
See preview:
https://deploy-preview-5342--daocloud-docs.netlify.app/kpanda/user-guide/nodes/taints

Update taint desc to fix issue #5247

---

docs/en/docs/ghippo/user-guide/audit/audit-log.md

[en]: update user-guide/audit/audit-log

---

docs/zh/docs/storage/hwameistor/intro/resources.md

Fix discussion #1671 in hwameistor/intro/resources

---

docs/zh/docs/videos/virtnest.md
docs/zh/navigation.yml

See preview:
https://deploy-preview-5352--daocloud-docs.netlify.app/videos/virtnest

Add a video to virtnest

---

docs/en/docs/virtnest/best-practice/import-ubuntu.md

Update en version according to #5366

[en]update virtnest-import-ubuntu

---

docs/zh/docs/kpanda/best-practice/k3s-lcm.md
docs/zh/navigation.yml

add k3s lcm best practice
See preview:
https://deploy-preview-5388--daocloud-docs.netlify.app/kpanda/best-practice/k3s-lcm

add k3s lcm best practice

---

docs/en/docs/dce/dce-rn/20231130.md
docs/en/docs/install/commercial/deploy-requirements.md
docs/en/docs/kpanda/user-guide/storage/sc.md
docs/en/docs/storage/hwameistor/install/deploy-operator.md
docs/en/docs/storage/hwameistor/install/deploy-ui.md
docs/en/docs/storage/hwameistor/install/drbdinstall.md
docs/en/docs/storage/hwameistor/releasenotes.md

[en]: Fix DRDB to DRBD 

---

docs/en/docs/amamba/user-guide/namespace/namespace.md
docs/en/docs/insight/user-guide/collection-manag/probe-module.md
docs/en/docs/insight/user-guide/dashboard/dashboard.md
docs/en/docs/insight/user-guide/dashboard/import-dashboard.md
docs/en/docs/insight/user-guide/infra/container.md
docs/en/docs/insight/user-guide/infra/namespace.md
docs/en/docs/insight/user-guide/infra/probe.md
docs/en/docs/insight/user-guide/trace/service.md
docs/en/docs/kant/user-guide/node/managed-node.md
docs/en/docs/network/modules/sriov-network-operator/install.md

unified the expression of "bar"

[en]replace 'pane' with 'bar'

---

docs/en/docs/storage/hwameistor/resources/volume-eviction.md

- Update the English version to be consistent with the Chinese version
- MTPE

[en]: Update hwameistor/resources/volume-eviction

---

docs/en/docs/storage/hwameistor/resources/volume-snapshot.md
docs/en/navigation.yml

[en]: add hwameistor/resources/volume-snapshot

---

docs/zh/navigation.yml

fix: adjust the insight nav

---

docs/zh/docs/kpanda/user-guide/gpu/nvidia/rhel9.2_offline_install_driver.md
docs/zh/navigation.yml

See preview:
https://deploy-preview-5417--daocloud-docs.netlify.app/kpanda/user-guide/gpu/nvidia/rhel9.2_offline_install_driver

add rhel9.2 driver offline install doc

---

docs/en/docs/blogs/230815-k8s1.28.md
docs/en/docs/community/hwameistor.md
docs/en/docs/community/piraeus.md
docs/en/docs/ghippo/best-practice/system-message.md
docs/en/docs/kangaroo/intro/faq.md
docs/en/docs/kangaroo/intro/index.md
docs/en/docs/kangaroo/managed/harbor.md
docs/en/docs/kant/user-guide/edge-app/create-batch-app.md
docs/en/docs/kant/user-guide/edge-app/index.md
docs/en/docs/kpanda/intro/release-notes.md
docs/en/docs/kpanda/user-guide/workloads/create-statefulset.md
docs/en/docs/middleware/mysql/user-guide/view.md
docs/en/docs/mspider/user-guide/multicluster/cluster-interconnect.md
docs/en/docs/mspider/user-guide/multicluster/multicluster-install.md
docs/en/docs/native/open.md
docs/en/docs/network/intro/releasenotes.md
docs/en/docs/network/modules/calico/install.md
docs/en/docs/network/modules/cilium/cross-cluster.md
docs/en/docs/network/modules/ingress-nginx/mirror.md
docs/en/docs/storage/hwameistor/resources/volume-ProvisionedIO.md
docs/en/docs/storage/index.md
docs/en/docs/storage/solutions/openebs.md
docs/en/docs/storage/terms/cas.md
docs/en/docs/storage/terms/k8s_storage.md
docs/en/docs/videos/kairship.md
docs/en/docs/videos/kpanda.md

Fix typos related to issue 4956

---

docs/zh/docs/ghippo/user-guide/access-control/ldap.md
docs/zh/docs/ghippo/user-guide/audit/gproduct-audit/kpanda.md
docs/zh/docs/ghippo/user-guide/workspace/quota.md
docs/zh/docs/kpanda/user-guide/gpu/nvidia/install_nvidia_driver_of_operator.md

See preview:
https://deploy-preview-5421--daocloud-docs.netlify.app/ghippo/user-guide/access-control/ldap

update ldap, audit-kpanda, workspace-quota, and install-nvidia-operator

---

docs/en/docs/insight/quickstart/install/gethosturl.md
docs/zh/docs/insight/quickstart/install/gethosturl.md

[en]update insight-quickstart gethosturl

---

docs/en/docs/ghippo/user-guide/workspace/quota.md

[en]: update user-guide/workspace/quota

---

docs/en/docs/ghippo/user-guide/audit/gproduct-audit/kpanda.md

[en]: update audit/gproduct-audit/kpanda

---

docs/en/docs/ghippo/user-guide/access-control/ldap.md

[en]: update tables in user-guide/access-control/ldap

---

docs/zh/docs/amamba/user-guide/gitops/integrate-argocd-ui.md

Fix https://github.com/DaoCloud/DaoCloud-docs/pull/5278#discussion_r1738090046

fix some code in integrate-argocd-ui.md

---

docs/en/docs/mspider/intro/release-notes.md
docs/zh/docs/mspider/intro/release-notes.md

See preview: https://deploy-preview-5463--daocloud-docs.netlify.app/en/mspider/intro/release-notes

update mspider release notes in en and zh

---

docs/en/docs/storage/hwameistor/resources/lvm-nodes.md

Update in English based on the Chinese text

[en]: Update hwameistor/resources/lvm-nodes

---

docs/en/docs/storage/solutions/dce-rook-ceph.md

Fixed in English based on the Chinese text

[en]: Fix the code block format in storage/solutions/dce-rook-ceph

---

docs/en/docs/storage/solutions/openebs-helm.md
docs/zh/docs/storage/solutions/openebs-helm.md

update in English text based on the Chinese text

[en]: Update storage/solutions/openebs-helm

---

docs/en/docs/virtnest/intro/release-notes.md

[en]update virtnest releasenotes

---

docs/en/docs/kairship/intro/release-notes.md

[en]update Kairship releasenote

---

docs/en/docs/network/modules/spiderpool/public-cloud/alibabacloud.md
docs/zh/docs/network/modules/spiderpool/public-cloud/alibabacloud.md

Update En version to keep in line with zh version and UI
See preview:
https://deploy-preview-5486--daocloud-docs.netlify.app/en/network/modules/spiderpool/public-cloud/alibabacloud

[en]: Update spiderpool/public-cloud/alibabacloud

---

docs/en/docs/ghippo/install/offline-install.md

Update en version to keep in line with zh version
See preview:
https://deploy-preview-5490--daocloud-docs.netlify.app/en/ghippo/install/offline-install

[en]: update ghippo/install/offline-install

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.21.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.21.0

download: addon version updated to v0.21.0

---

docs/en/docs/download/addon/history.md
docs/en/docs/download/addon/v0.21.0.md
docs/en/docs/download/index.md

Update after #5497 
See preview:
https://deploy-preview-5498--daocloud-docs.netlify.app/en/download/addon/v0.21.0

[en] Add addon v0.21.0 to download

---

docs/en/docs/kpanda/user-guide/security/cis/report.md
docs/zh/docs/kpanda/user-guide/security/cis/report.md

update cis report to fix issue #5476

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.21.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.21.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.21.0

download: dce5 version updated to v0.21.0

---

docs/en/docs/download/business/dce5-installer-history.md
docs/en/docs/download/business/dce5-installer-v0.21.0.md
docs/en/docs/download/free/dce5-installer-history.md
docs/en/docs/download/free/dce5-installer-v0.21.0.md
docs/en/docs/download/index.md
docs/zh/docs/download/business/dce5-installer-v0.21.0.md
docs/zh/docs/download/free/dce5-installer-v0.21.0.md

[en] Add dce5 download pages to v0.21.0

---

docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/k8s-install/ocp-install-dce5.0.md
docs/en/docs/install/os-install/neokylin-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/zh/docs/install/commercial/start-install.md
docs/zh/docs/install/community/k8s/k8s-dce-deploy.md

[en] update installer pages to v0.21.0

---

docs/en/docs/network/intro/releasenotes.md

[en]: Update network/intro/releasenotes

---

docs/zh/docs/kpanda/user-guide/backup/install-velero.md

fix missing para desc mentioned in issue #5383

---

docs/en/docs/storage/hwameistor/releasenotes.md
docs/zh/docs/storage/hwameistor/releasenotes.md

Update en version to keep in line with zh version and UI

[en]: Update storage/hwameistor/releasenotes

---

docs/zh/docs/kpanda/user-guide/scale/install-metrics-server.md

Fix #5527 
See preview: https://deploy-preview-5529--daocloud-docs.netlify.app/kpanda/user-guide/scale/install-metrics-server

update install-metrics-server.md to fix issue #5527

---

docs/en/docs/storage/hwameistor/resources/storageclass.md
docs/zh/docs/storage/hwameistor/resources/storageclass.md

fix an issue #5097 in hwameistor/resources/storageclass

---

docs/en/docs/ghippo/user-guide/report-billing/gmagpie-offline-install.md
docs/zh/docs/ghippo/user-guide/report-billing/gmagpie-offline-install.md

update doc about install offline gmagpie

---

docs/zh/docs/virtnest/best-practice/import-ubuntu.md
docs/zh/docs/virtnest/best-practice/import-windows.md
docs/zh/docs/virtnest/gpu/vm-gpu.md
docs/zh/docs/virtnest/gpu/vm-vgpu.md

See preview:
https://deploy-preview-5537--daocloud-docs.netlify.app/virtnest/best-practice/import-ubuntu

import vm delete vddk image create info

---

docs/en/docs/virtnest/best-practice/import-ubuntu.md
docs/en/docs/virtnest/best-practice/import-windows.md
docs/en/docs/virtnest/gpu/vm-gpu.md
docs/en/docs/virtnest/gpu/vm-vgpu.md

Update according to #5537 
Delete contents related to vddk image create

[en]update virtnest docs

---

docs/zh/docs/dce/features.md

Fix #5554 
See preview:
https://deploy-preview-5556--daocloud-docs.netlify.app/dce/features

update dce/features.md to fix issue 5554

---

docs/en/docs/insight/quickstart/otel/operator.md

update after #5505 
See preview:
https://deploy-preview-5557--daocloud-docs.netlify.app/en/insight/quickstart/otel/operator

[en]update insight-otel-operator

---

docs/en/docs/storage/solutions/dce-longhorn.md

Update the code in English according to the changes in Chinese

[en]: Update solutions/dce-longhorn

---

docs/en/docs/network/modules/spiderpool/releasenotes.md
docs/zh/docs/network/modules/spiderpool/releasenotes.md

Update English to keep in line with Chinese

[en]: Update spiderpool/releasenotes.md

---

docs/zh/docs/install/commercial/cluster-config.md

update v1alpha3 to v1alpha4 in cluster-config.md

---

docs/en/docs/network/intro/releasenotes.md
docs/zh/docs/network/intro/releasenotes.md

Update the English page based on the Chinese page
see preview: https://deploy-preview-5575--daocloud-docs.netlify.app/en/network/intro/releasenotes

[en]: update v0.15.1 in network/intro/releasenotes

---

docs/en/docs/insight/reference/used-metric-in-insight.md
docs/en/navigation.yml

According to Chinese version, add a metrics-reference doc to Insight module.

[en]Add a doc to Insight-reference

---

docs/en/docs/ghippo/user-guide/report-billing/index.md

Update and modify the English page based on the Chinese page and UI

[en]: update user-guide/report-billing/index

---

docs/zh/docs/ghippo/troubleshooting/ghippo03.md

https://gitlab.daocloud.cn/ndx/ghippo/-/issues/1443

optimize ghippo keycloak table number

---

docs/en/docs/kairship/intro/offline-upgrade.md
docs/en/docs/kairship/resource/update-ns.md

Fix some typos in kairship docs

[en]MTPE of kairship docs

---

docs/en/docs/storage/hwameistor/intro/drbd-support.md

Fixed typos in the English title

[en]: Fixed typos in hwameistor/intro/drbd-support

---

docs/en/docs/ghippo/user-guide/audit/open-k8s-audit.md
docs/zh/docs/ghippo/user-guide/audit/open-k8s-audit.md

修改文档：https://docs.daocloud.io/ghippo/user-guide/audit/open-k8s-audit/

update ghippo audit doc

---

docs/en/docs/insight/user-guide/collection-manag/probe-module.md
docs/zh/docs/insight/user-guide/collection-manag/probe-module.md

Update after #5602
see preview: https://deploy-preview-5605--daocloud-docs.netlify.app/en/insight/user-guide/collection-manag/probe-module

[en]: Update insight probe method docs

---

docs/en/docs/insight/quickstart/install/upgrade-note.md
docs/zh/docs/insight/quickstart/install/upgrade-note.md

Update English to keep in line with Chinese
Fix typos in English and Chinese

[en]: Update insight-agent/upgrade-note and fix typos

---

docs/en/docs/insight/best-practice/tail-based-sampling.md
docs/zh/docs/insight/best-practice/tail-based-sampling.md

- Update English based on Chinese
- MTPE

[en]: Update best-practice/tail-based-sampling

---

docs/en/docs/virtnest/quickstart/update.md

Update after #5621
preview: https://deploy-preview-5624--daocloud-docs.netlify.app/en/virtnest/quickstart/update

[en]: Update virtnest/quickstart/update

---

docs/zh/docs/kpanda/best-practice/kubean-low-version.md

1. 文档中与kubean 的k8s支持版本范围不一致
2.  cd data 后apply无需再加上data目录

update kubean low version range

---

docs/zh/docs/kpanda/best-practice/update-offline-cluster.md

enhance upgrade cluster doc

---

docs/zh/docs/virtnest/vm/cross-cluster-migrate.md
docs/zh/navigation.yml

See preview:
https://deploy-preview-5639--daocloud-docs.netlify.app/virtnest/vm/cross-cluster-migrate

virtnest-cross-cluster-migratie

---

docs/en/docs/virtnest/vm/cross-cluster-migrate.md
docs/en/navigation.yml
docs/zh/docs/virtnest/vm/cross-cluster-migrate.md
docs/zh/navigation.yml

Update after #5639
see preview: https://deploy-preview-5642--daocloud-docs.netlify.app/en/virtnest/vm/cross-cluster-migrate

 [en]: Add a new page about cross-cluster-migrate

---

docs/en/docs/kant/intro/features.md
docs/en/docs/virtnest/gpu/vm-gpu.md
docs/en/docs/virtnest/gpu/vm-vgpu.md

Update English version to keep in line with Chinese version

[en]: Update kant/intro/features, virtnest/gpu/vm-gpu and vm-gpu

---

docs/zh/navigation.yml

Fix these issues in nav:
```
WARNING -  A reference to 'amamba/user-guide/quickstart/pipeline-kairship.md' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A reference to 'kpanda/user-guide/gpu/usemetax.md' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A reference to 'kangaroo/integrate/registry-space.md' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A reference to 'kangaroo/integrate/bind-to-ws.md' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A reference to 'kangaroo/integrate/sync.md' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING -  A …
```

fix 404 caused by wrong path in nav

---

docs/en/docs/ghippo/user-guide/audit/gproduct-audit/insight.md

[en]: Update insight audit

---

docs/en/docs/insight/quickstart/install/component-scheduling.md
docs/zh/docs/insight/quickstart/install/component-scheduling.md

Fix some typographical errors and optimize format in en and zh version

Fix and optimize component-scheduling

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.22.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.22.0

download: addon version updated to v0.22.0

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.22.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.22.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.22.0

download: dce5 version updated to v0.22.0

---

docs/en/docs/install/commercial/cluster-config.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/os-install/neokylin-install-dce5.0.md
docs/en/docs/install/release-notes.md
docs/zh/docs/install/commercial/cluster-config.md
docs/zh/docs/install/commercial/start-install.md
docs/zh/docs/install/release-notes.md

Update en pages after PR #5700

[en] update installer pages to v0.22.0

---

docs/en/docs/community/kasmcloud.md
docs/zh/docs/community/kasmcloud.md

Fix image and anchors in kasmcloud.md

---

docs/en/docs/baize/developer/inference/models.md
docs/en/docs/dce/dce-rn/20240430.md
docs/en/docs/dce/dce-rn/20240530.md
docs/en/docs/dce/dce-rn/20240630.md
docs/en/docs/dce/dce-rn/20240730.md
docs/en/docs/dce/dce-rn/20240830.md
docs/en/docs/videos/baize.md
docs/zh/docs/baize/developer/inference/models.md
docs/zh/docs/dce/dce-rn/20240430.md
docs/zh/docs/dce/dce-rn/20240530.md
docs/zh/docs/dce/dce-rn/20240630.md
docs/zh/docs/dce/dce-rn/20240730.md
docs/zh/docs/dce/dce-rn/20240830.md
docs/zh/docs/videos/baize.md
docs/zh/docs/videos/use-cases.md

fix links in baize folder

---

docs/zh/docs/native/git/video.md
docs/zh/docs/native/git/works.md

fix links in native folder

---

docs/en/docs/dce/bphome.md
docs/en/docs/dce/dce-rn/20240330.md
docs/en/docs/dce/dce-rn/20240430.md
docs/en/docs/virtnest/intro/index.md
docs/zh/docs/dce/bphome.md
docs/zh/docs/dce/dce-rn/20240330.md
docs/zh/docs/dce/dce-rn/20240430.md
docs/zh/docs/virtnest/intro/faq.md
docs/zh/docs/virtnest/intro/index.md
docs/zh/docs/virtnest/quickstart/index.md

fix links in virtnest folder

---

docs/zh/docs/download/index.md

See preview:
https://deploy-preview-5740--daocloud-docs.netlify.app/download/#_4

update submodule table: download/index

---

docs/en/docs/download/index.md
docs/en/docs/download/modules/ipavo.md
docs/en/navigation.yml
docs/zh/docs/download/index.md
docs/zh/docs/download/modules/ipavo.md
docs/zh/navigation.yml

ipavo offline pkg download page

download page for ipavo

---

docs/en/navigation.yml
docs/zh/docs/dce/dce-rn/20240930.md
docs/zh/navigation.yml

See preview:
https://deploy-preview-5745--daocloud-docs.netlify.app/dce/dce-rn/20240930

Add release notes dce5.0-20240930

---

docs/en/docs/ghippo/user-guide/access-control/iam.md
docs/zh/docs/ghippo/user-guide/access-control/iam.md

增加 ghippo 访问控制的流程图
see preview: https://deploy-preview-5773--daocloud-docs.netlify.app/ghippo/user-guide/access-control/iam#_3

Add mermaid to access-control

---

docs/zh/docs/install/evolve.md
docs/zh/docs/install/upgrade-des.md
docs/zh/docs/install/upgrade.md
docs/zh/navigation.yml

- docs/zh/docs/install/upgrade-des.md 内容很少，没必要存在，所以先删除
- 其他文字优化

update install/evolve and upgrade

---

docs/zh/docs/baize/developer/quick-start.md

update and fix typo in developer/quick-start.md

---

docs/zh/docs/kpanda/best-practice/update-offline-cluster.md
docs/zh/docs/kpanda/intro/faq.md
docs/zh/navigation.yml

更新内容：
1. 工作集群离线升级指南新增 部署场景，对应 issue：https://gitlab.daocloud.cn/ndx/engineering/kpanda/-/issues/4654；
2. 更新 FAQ，对应 issue：https://gitlab.daocloud.cn/ndx/engineering/kpanda/-/issues/4778

kpanda update user guide

---

docs/zh/docs/kpanda/intro/faq.md

Fix #5783 
新增页面索引，方便信息检索
See preview:
https://deploy-preview-5784--daocloud-docs.netlify.app/kpanda/intro/faq#permissions

Add index to kpanda/intro/faq.md

---

docs/zh/docs/mspider/install/install.md

Fix https://github.com/DaoCloud/DaoCloud-docs/issues/5790#issuecomment-2421778050

Fix helm upgrade command with --set

---

docs/en/docs/amamba/user-guide/pipeline/jenkins-metric.md
docs/en/navigation.yml
docs/zh/docs/amamba/user-guide/pipeline/jenkins-metric.md

- Update zh page
- Add en page

update pipeline/jenkins-metric.md and add en version

---

docs/zh/docs/kpanda/intro/faq.md

update structure of kpanda/intro/faq.md

---

docs/zh/docs/dce/faq.md
docs/zh/navigation.yml

增加一个常见问题/故障排查的检索页面
See preview:
https://deploy-preview-5822--daocloud-docs.netlify.app/dce/faq

Add a faq index

---

docs/zh/docs/dce/index.md
docs/zh/docs/index.md

Add bp and faq to home and index

---

docs/en/docs/community/kubean.md
docs/en/docs/kpanda/best-practice/update-offline-cluster.md
docs/zh/docs/community/kubean.md
docs/zh/docs/kpanda/best-practice/update-offline-cluster.md

[en] update update-offline-cluster.md

---

docs/zh/docs/dce/faq.md
docs/zh/docs/middleware/mysql/faq/faq-others.md

See preview:
https://deploy-preview-5837--daocloud-docs.netlify.app/middleware/mysql/faq/faq-others#operator-mysql-1045

Update mysql faq and add a new to faq-index

---

docs/zh/docs/middleware/mysql/faq/faq-master-slave.md

See preview:
https://deploy-preview-5839--daocloud-docs.netlify.app/middleware/mysql/faq/faq-master-slave

Fix format in mysql/faq/faq-master-slave.md

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.23.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.23.0

download: addon version updated to v0.23.0

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.23.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.23.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.23.0

download: dce5 version updated to v0.23.0

---

docs/en/docs/dce/roadmap.md
docs/en/navigation.yml

[en] add product roadmap

---

.github/workflows/pull-request-test.yaml
docs/en/mkdocs.yml
docs/en/theme/overrides/partials/content.html
docs/en/theme/overrides/partials/source-file.html
docs/zh/mkdocs.yml
docs/zh/theme/overrides/partials/content.html
requirements.txt

add commiter style

---

docs/zh/docs/mspider/troubleshoot/istio-init-failed.md
docs/zh/navigation.yml

See preview:
https://deploy-preview-5980--daocloud-docs.netlify.app/mspider/troubleshoot/istio-init-failed

mspider: add docs for troubleshot with istio init failed

---

docs/en/docs/install/upgrade.md
docs/zh/docs/install/upgrade.md

Add warning text to install/upgrade.md

---

docs/zh/docs/kpanda/best-practice/get-kubeconfig.md
docs/zh/navigation.yml

See preview:
https://deploy-preview-5986--daocloud-docs.netlify.app/kpanda/best-practice/get-kubeconfig

kpanda: add docs for how get permanently token with eks and gke

---

docs/en/docs/kpanda/best-practice/get-kubeconfig.md
docs/en/navigation.yml

[en] Add best-practice/get-kubeconfig.md

---

docs/en/docs/download/index.md
docs/zh/docs/download/index.md

Fix links to addon v0.23.0

---

docs/zh/docs/download/addon/history.md
docs/zh/docs/download/addon/v0.24.0.md
docs/zh/docs/download/index.md

download: addon version updated to v0.24.0

download: addon version updated to v0.24.0

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.24.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.24.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.24.0

download: dce5 version updated to v0.24.0

---

docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/zh/docs/install/commercial/start-install.md

[en] update installer version to v0.24.0

---

docs/zh/docs/install/best-practices/all-in-one-machine.md
docs/zh/docs/install/best-practices/extend-params.md
docs/zh/docs/install/best-practices/thinder-ha.md
docs/zh/docs/install/commercial/external/external-binary.md
docs/zh/docs/install/commercial/external/external-imageandchart.md
docs/zh/docs/install/commercial/external/external-middlewares.md
docs/zh/docs/install/commercial/external/external-os.md
docs/zh/docs/install/community/k8s/offline.md
docs/zh/docs/install/community/k8s/online.md
docs/zh/docs/install/k8s-install/ecs-install-dce5.0.md
docs/zh/docs/install/k8s-install/ocp-install-dce5.0.md
docs/zh/docs/install/upgrade.md

installer version 0.19.0, update cc apiversion to provision.daocloud.io/v1alpha4

update cc apiversion

---

docs/zh/docs/kant/intro/faq.md
docs/zh/navigation.yml

kant add faq

---

docs/zh/docs/virtnest/vm/cross-cluster-migrate.md

相关链接：https://docs.daocloud.io/virtnest/vm/cross-cluster-migrate/
更新了 跨集群迁移相关文档

[zh] update docs/zh/docs/virtnest/vm/cross-cluster-migrate.md

---

docs/en/docs/kpanda/best-practice/kubean-low-version.md
docs/zh/docs/kpanda/best-practice/kubean-low-version.md

use yaml for consistency in a single page

---

docs/zh/docs/download/business/dce5-installer-history.md
docs/zh/docs/download/business/dce5-installer-v0.25.0.md
docs/zh/docs/download/free/dce5-installer-history.md
docs/zh/docs/download/free/dce5-installer-v0.25.0.md
docs/zh/docs/download/index.md

download: dce5 version updated to v0.25.0

download: dce5 version updated to v0.25.0

---

docs/en/docs/amamba/user-guide/namespace/multi-namespace.md
docs/en/docs/amamba/user-guide/namespace/namespace.md
docs/en/navigation.yml
docs/zh/navigation.yml

update multicloud namespace

---

docs/zh/docs/download/addon/.template.md

See https://gitlab.daocloud.cn/ndx/engineering/addon-pack/-/merge_requests/707/diffs#6cca508d3ff0a26769c7124b3993fc0b7559bb0a_140_139
fix https://gitlab.daocloud.cn/ndx/engineering/addon-pack/-/merge_requests/707/diffs#6cca508d3ff0a26769c7124b3993fc0b7559bb0a_140_139

update addon kant-agent

---

docs/en/docs/network/modules/spiderpool/install/install.md
docs/zh/docs/network/modules/spiderpool/install/install.md

[en] update spiderpool/install/install.md

---

docs/zh/docs/dce/dce-rn/20250131.md
docs/zh/navigation.yml

Add new release notes for DCE 5.0-20250131

Add dce-rn/20250131.md

---

docs/en/mkdocs.yml
docs/zh/mkdocs.yml

chore(mkdocs.yml): disable auto git-commiter plugin

---

docs/zh/docs/kpanda/best-practice/create-redhat9.2-on-centos-platform.md

Correct the import package command

update best practice of create redhat9.2

---

docs/zh/docs/install/commercial/start-install.md
docs/zh/docs/install/community/k8s/k8s-dce-deploy.md
docs/zh/docs/install/community/k8s/offline.md
docs/zh/docs/install/community/k8s/online.md
docs/zh/docs/install/community/kind/online.md

update installer version to v0.27.0

update installer version to v0.27.0 

---

docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/zh/docs/install/community/kind/online.md

[en] update installer version to v0.27.0

---

docs/en/docs/insight/quickstart/otel/operator.md
docs/zh/docs/insight/quickstart/otel/operator.md

[en] update quickstart/otel/operator.md

---

docs/en/mkdocs.path.yaml
docs/en/mkdocs.yml
docs/zh/mkdocs.path.yaml
docs/zh/mkdocs.yml

add more redirects to fix broken links

---

docs/en/docs/baize/best-practice/finetunel-llm.md
docs/zh/docs/baize/best-practice/finetunel-llm.md

Replace an image with mermaid

---

docs/en/docs/dce/license0.md
docs/en/docs/ghippo/best-practice/authz-plan.md
docs/en/docs/ghippo/best-practice/cluster-for-multiws.md
docs/en/docs/ghippo/install/login.md
docs/en/docs/ghippo/intro/features.md
docs/en/docs/ghippo/user-guide/access-control/iam.md
docs/en/docs/ghippo/user-guide/password.md
docs/en/docs/install/index.md
docs/en/docs/kangaroo/best-practice/managed-harbor-select-access-type.md
docs/en/docs/kant/user-guide/node/index.md
docs/en/docs/middleware/index.md
docs/en/docs/mspider/best-practice/optimize-sidecar-resource.md
docs/en/docs/mspider/intro/comp-archi-ui/architect.md
docs/zh/docs/ghippo/best-practice/cluster-for-multiws.md
docs/zh/docs/ghippo/install/login.md
docs/zh/docs/ghippo/intro/features.md
docs/zh/docs/ghippo/user-guide/access-control/iam.md
docs/zh/docs/ghippo/user-guide/password.md
docs/zh/docs/install/index.md
docs/zh/docs/kangaroo/best-practice/managed-harbor-select-access-type.md
docs/zh/docs/kant/user-guide/edge-network/index.md
docs/zh/docs/kant/user-guide/node/index.md
docs/zh/docs/middleware/index.md
docs/zh/docs/mspider/best-practice/optimize-sidecar-resource.md
docs/zh/docs/mspider/intro/comp-archi-ui/architect.md

Fix #6355 
See preview:
https://deploy-preview-6356--daocloud-docs.netlify.app/en/dce/license0

update classDef k8s color

---

docs/en/docs/dce/index.md
docs/en/docs/install/index.md
docs/zh/docs/install/index.md

Fix some links found by:
https://www.drlinkcheck.com/account/subscriptions/1/projects/2/reports/all-issues

fix links to intro/index.md

---

docs/zh/docs/insight/quickstart/otel/golang/golang.md
docs/zh/docs/insight/quickstart/otel/golang/traceid_logs.md
docs/zh/navigation.yml

See preview:
- https://deploy-preview-6369--daocloud-docs.netlify.app/insight/quickstart/otel/java/mdc
- https://deploy-preview-6369--daocloud-docs.netlify.app/insight/quickstart/otel/golang/traceid_logs

[Insight] add golang traces with logs docs

---

docs/zh/docs/kpanda/user-guide/helm/Import-addon.md

The original page is:
https://docs.daocloud.io/kpanda/user-guide/helm/

Fix 1-2-3 list in helm/Import-addon.md

---

docs/zh/docs/install/commercial/start-install.md
docs/zh/docs/install/community/k8s/k8s-dce-deploy.md
docs/zh/docs/install/community/k8s/offline.md
docs/zh/docs/install/community/k8s/online.md
docs/zh/docs/install/community/kind/online.md

update installer version to v0.28.0

update installer version to v0.28.0

---

docs/en/docs/install/air-tag-download.md
docs/en/docs/install/commercial/download-file.md
docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/community/kind/online.md
docs/en/docs/install/install-tools.md
docs/en/docs/install/k8s-install/ecs-install-dce5.0.md
docs/zh/docs/install/air-tag-download.md
docs/zh/docs/install/commercial/download-file.md
docs/zh/docs/install/commercial/start-install.md
docs/zh/docs/install/install-tools.md
docs/zh/docs/install/k8s-install/ecs-install-dce5.0.md
docs/zh/docs/install/light-install/install-light.md

[en] Update installer to v0.28.0

---

docs/en/docs/ghippo/user-guide/audit/open-k8s-audit.md
docs/zh/docs/ghippo/user-guide/audit/open-k8s-audit.md

use `<details>` to hide/show the yaml content
See preview:
https://deploy-preview-6401--daocloud-docs.netlify.app/ghippo/user-guide/audit/open-k8s-audit

update yaml in open-k8s-audit.md

---

docs/en/docs/ghippo/user-guide/audit/open-k8s-audit.md
docs/zh/docs/ghippo/user-guide/audit/open-k8s-audit.md

https://gitlab.daocloud.cn/ndx/engineering/insight/insight/-/issues/1964

adjust k8 audit config file format for kube-apiserver.yaml

---

docs/en/docs/insight/quickstart/otel/operator.md
docs/zh/docs/insight/quickstart/otel/operator.md

update insight otel operator doc
https://deploy-preview-6409--daocloud-docs.netlify.app/insight/quickstart/otel/operator#demo
https://deploy-preview-6409--daocloud-docs.netlify.app/en/insight/quickstart/otel/operator#automatic-injection-demo

insight: update otel operator doc

---

docs/zh/docs/install/commercial/deploy-requirements.md
docs/zh/docs/install/commercial/start-install.md

1. Update os requirement;
2. Update resource requirements；
3. Update os package.

update deploy requirement

---

docs/en/mkdocs.yml

update redirects in en/mkdocs.yml

---

docs/zh/navigation.yml

follow up https://github.com/DaoCloud/DaoCloud-docs/pull/6431

add navigation for kafka optimize

---

docs/en/docs/ghippo/best-practice/authz-plan.md
docs/zh/docs/ghippo/best-practice/authz-plan.md

Fix #6455 
Fix https://gitlab.daocloud.cn/ndx/ghippo/-/issues/1614

Fix mermaid list in authz-plan.md

---

docs/zh/docs/dce/dce-rn/20250430.md
docs/zh/navigation.yml

Add dce-rn/20250430.md

---

docs/en/docs/dce/dce-rn/20250331.md
docs/en/docs/dce/dce-rn/20250430.md
docs/zh/docs/dce/dce-rn/20250331.md
docs/zh/docs/dce/dce-rn/20250430.md

Update versions supported by installer and kubean

---

docs/en/docs/install/commercial/start-install.md
docs/en/docs/install/community/k8s/k8s-dce-deploy.md
docs/en/docs/install/community/k8s/offline.md
docs/en/docs/install/community/k8s/online.md
docs/en/docs/install/release-notes.md
docs/zh/docs/install/community/k8s/offline.md
docs/zh/docs/install/community/k8s/online.md

Sync with en #6476 
Related to #6467

[en] update installer to v0.29.0

---

docs/zh/docs/dce/dce-rn/20250331.md
docs/zh/docs/dce/dce-rn/20250430.md

Fix version number in 20250331.md and 20250430.md

---

docs/en/docs/kairship/crds/crd.md
docs/en/docs/kpanda/user-guide/custom-resources/create.md
docs/zh/docs/kairship/crds/crd.md
docs/zh/docs/kpanda/user-guide/custom-resources/create.md

fix a CRD yaml

---

docs/en/docs/insight/user-guide/collection-manag/service-monitor.md
docs/zh/docs/insight/user-guide/collection-manag/service-monitor.md

insight: update servicemonitor yaml

---

docs/en/docs/network/intro/release-notes.md
docs/zh/docs/network/intro/release-notes.md

https://docs.daocloud.io/network/intro/release-notes

修正云原生网络 vlanid 相关注解描述错误

---

docs/zh/docs/kant/user-guide/node/access-guide-v0.19.md
docs/zh/docs/kant/user-guide/node/access-guide.md

- Try to add tabs
- Make keadm commands easier to read
See preview:
https://deploy-preview-6562--daocloud-docs.netlify.app/kant/user-guide/node/access-guide#__tabbed_1_1

update kant: node/access-guide.md

---

docs/en/docs/hydra/api-call.md
docs/en/docs/hydra/apikey.md
docs/en/docs/hydra/dataset.md
docs/en/docs/hydra/deploy/deploy.md
docs/en/docs/hydra/deploy/index.md
docs/en/docs/hydra/exp.md
docs/en/docs/hydra/index.md
docs/en/docs/hydra/intro/index.md
docs/en/docs/hydra/intro/release-notes.md
docs/en/docs/hydra/oam/index.md
docs/en/docs/hydra/oam/mdm.md
docs/en/docs/hydra/user-guides/bob-translate.md
docs/en/docs/hydra/user-guides/cherry-studio.md
docs/en/docs/hydra/user-guides/cline-in-vscode.md
docs/en/docs/hydra/user-guides/index.md
docs/en/docs/hydra/user-guides/lobe-chat.md
docs/en/navigation.yml

[en] Add 16 pages to hydra

---

docs/zh/docs/amamba/user-guide/wizard/jar-java-app.md

fix 404 link to a jar package

---

.github/workflows/code-review.yml

Try to add gemini-review bot

---

.github/workflows/code-review.yml

Add feedback after typing gemini-review

---

docs/en/docs/dce/dce-rn/20250731.md
docs/en/navigation.yml
docs/zh/docs/dce/dce-rn/20250731.md
docs/zh/navigation.yml

Add dce-rn/20250731.md

---

docs/zh/docs/network/modules/sriov-network-operator/ai-sriov.md
docs/zh/navigation.yml

网络新增一篇文档：使用 SR-IOV 构建 AI 集群
cc @Adityayxt

Add sriov-network-operator/ai-sriov.md

---

docs/zh/docs/network/modules/cilium/deploy-cilium.md
docs/zh/navigation.yml

The source is:
https://github.com/windsonsea/deployCilium

Add cilium/deploy-cilium.md

---

docs/en/mkdocs.path.yaml
docs/en/mkdocs.yml
docs/zh/mkdocs.path.yaml
docs/zh/mkdocs.yml

enable use_directory_urls

---

docs/en/docs/dce/dce-rn/20250831.md
docs/en/navigation.yml
docs/zh/docs/dce/dce-rn/20250831.md

[en] Add dce-rn/20250831.md

---

docs/zh/docs/insight/user-guide/collection-manag/collection-manag.md

增加 ServiceMonitor PodMonitor 和 ScrapeConfig 配置说明

insight: update insight-scrape-config
