DaoCloud/DaoCloud-docs

pages/21.allen-docker/01.docker-logs/docs.md, pages/21.allen-docker/02.docker-exec/docs.md, pages/21.allen-docker/03.docker-lo-details/docs.md, pages/21.allen-docker/04.docker-fs/docs.md, pages/21.allen-docker/05.docker-image/docs.md, pages/21.allen-docker/06.docker-image-details/docs.md, pages/21.allen-docker/07.docker-json/docs.md, pages/21.allen-docker/08.docker-build-cache/docs.md, pages/21.allen-docker/09.docker-commit/docs.md, pages/21.allen-docker/10.docker-root/docs.md, pages/21.allen-docker/11.docker-key/docs.md
简化了allen谈docker具体文章的标题，否则标题显示不全文章名
=> simplify title

pages/15.python-docker/03.python-docker-002/docs.md
=> Change PHP to Python

pages/20.python-docker/02.docker-python-001/docs.md
=> add requirement.txt edit to tutorial

pages/16.daocloud-enterprise/04.install-for-production/docs.md
This PR did:
1. fix “－－” to "--"
2. fix typos ECE
3. change selinux to SELinux
4. delete lots of blank lines.
WDYT? @zhe
=> Update doc.md and fix typos

pages/08.daocloud-services/06.postgresql-services/docs.md
It seems that the current github repo url of phpPgAdmin is invalid and I found this repo can be built for my app.
https://github.com/yxwzaxns/DaoCloud_phpPgAdmin.git
=> update phpMyAdmin github repo url

pages/24.nodejs-docker/02.hello-docker/docs.md
根据Dockerfile最佳实践：CMD 与 ENTRYPOINT 命令请使用数组语法。
=> ENTRYPOINT 使用数组写法

pages/02.faq/01.what-is-daocloud/docs.md
E203: 中文标点与其他字符间一律不加空格
======================================
LINE: 80
技术应用研究白皮书」 文章链接，下载地址
　　　　　　　　　－-－
.......................................
=> Fixed Document Styles.

pages/05.ci-image-build/04.dockerfile/docs.md
=> 更新了关于Dockerfile的介绍

.github/workflows/main.yml
It pull request will do auto build docs website to ucloud s3 bucket with github workflow.
before the job working, u need add this secret key into project setting with action module
- UCLOUD_PUBLICKEY
- UCLOUD_PRIVATEKEY
- UCLOUD_REGION
- UCLOUD_BUCKET
=> Added github action workflow of build docs site

.github/workflows/main.yml
Split GitLab vs Github CI into different ucloud US3 buckets
=> Update github ci

.github/workflows/test.yml
=> add pr check

docs/zh/middleware/elastic-search/intro/features.md
=> Update es features.md

.github/workflows/main.yml, .github/workflows/test.yml, mkdocs-en.yml, mkdocs.yml, theme/overrides/partials/parallax/connect_en.html, theme/overrides/partials/parallax/expect_en.html, theme/overrides/partials/parallax/hero_en.html, theme/overrides/partials/parallax/spotlight_en.html, theme/overrides/partials/parallax/trust_en.html, theme/overrides/partials/parallax/users_en.html
- 更新了英文目录
- 添加了英文首页
@SAMZONG  need your review and confirm how to implement the en homepage.
=> updated  mkdocs-en.yml and en-homepage

docs/zh/dce/license0.md, docs/zh/install/install-dce.md, docs/zh/install/install-k8s.md, docs/zh/install/install-tools.md, docs/zh/install/install_prerequisite.sh, mkdocs.yml
=> added install steps

docs/zh/blogs/blog00.md, docs/zh/blogs/kpanda.md, docs/zh/community/index.md, docs/zh/dce/scenario.md, docs/zh/dce/what-is-dce.md, docs/zh/dce/whyus.md, docs/zh/middleware/midware.md, docs/zh/videos/index.md, mkdocs.yml
=> fix a title and add buttons

docs/zh/install/install-dce.md, docs/zh/install/install-k8s.md, docs/zh/install/install-tools.md
=> Updated text about install-dce

mkdocs-en.yml, mkdocs.yml
=> updated home name

docs/zh/install/install-dce.md, docs/zh/install/uninstall.md, mkdocs.yml
=> updated install steps

mkdocs-en.yml, mkdocs.yml
=> update offical website link

README.md, makefile, poetry.lock, pyproject.toml, requirements.txt
=> easy use makefile running daocloud-docs doc site

makefile
=> Fixed makefile

theme/main.html, theme_en/main.html
=> Added baidu tongji analysis code

docs/en/install/install-dce.md, docs/en/install/install-tools.md, docs/zh/install/install-dce.md, docs/zh/install/install-tools.md, docs/zh/install/offline-install.md
=> updated links of installation

docs/zh/release/rn5.0.md
=> updated release notes

.github/workflows/main.yml, .github/workflows/test.yml, mkdocs.yml, poetry.lock, pyproject.toml, requirements.txt, theme/404.html, theme_en/404.html
- upgrade theme/404.html page
- ass kdocs-redirects plugin
=> update theme 404 page desgin

docs/zh/network/modules/spiderpool/usage.md
Signed-off-by: iiiceoo <ziqian.xue@daocloud.io>
=> docs:Add spiderpool docs usage.md

docs/zh/network/modules/contour/what.md, docs/zh/network/modules/ingress-nginx/what.md, mkdocs.yml
=> [zh] Update ingress nav

docs/zh/kairship/05workload/yaml.md
- zh/kairship/05workload/yaml.md
=> update yaml sample fix no namespace statement

docs/zh/community/index.md, mkdocs.yml
=> adjust orders of opc and kafka

docs/zh/network/modules/f5networks/install.md, docs/zh/network/modules/f5networks/usage.md, docs/zh/network/modules/f5networks/what.md
=> updated f5network pages

docs/en/install/install-dce.md, docs/en/install/install-tools.md, docs/en/install/offline-intall.md, docs/en/install/uninstall.md, docs/zh/install/install-dce.md, mkdocs-en.yml
=> sync install steps with zh

docs/en/docs/network/intro/what-is-net.md, docs/zh/docs/network/intro/what-is-net.md
=> Fix typo: 'Metalb' -> 'MetalLB'

.github/workflows/main.yml, docs/en/mkdocs.yml, docs/en/navigation.yml, docs/zh/mkdocs.yml, docs/zh/navigation.yml, makefile
=> Fix makefile

.github/workflows/main.yml, .github/workflows/test.yml
=> fix workflow

docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang-ebpf.md, docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang.md, docs/zh/docs/insight/06UserGuide/01quickstart/otel/meter.md, docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md
=> update otel docs

docs/en/dce/features.md
Signed-off-by: 冉琪 <ranqi@ranqideMacBook-Air.local>
=> doc:translate dce features.md into english

makefile, scripts/word_count.py
=> update image version in makefile

docs/zh/docs/videos/mspider.md
=> added mspider video

docs/en/mkdocs.yml, docs/zh/mkdocs.yml
=> :fixed: can not use edit and view button

docs/en/theme/main.html, docs/en/theme/overrides/partials/parallax/connect.html, docs/en/theme/overrides/partials/parallax/hero.html, docs/en/theme/overrides/partials/parallax/spotlight.html, docs/en/theme/overrides/partials/parallax/trust.html, docs/zh/theme/main.html, docs/zh/theme/overrides/partials/parallax/connect.html, docs/zh/theme/overrides/partials/parallax/hero.html, docs/zh/theme/overrides/partials/parallax/spotlight.html, docs/zh/theme/overrides/partials/parallax/trust.html
=> :Fixed: bad doc links in theme

docs/en/theme/overrides/partials/parallax/spotlight.html, docs/zh/theme/overrides/partials/parallax/spotlight.html, scripts/refresh_cdn_cache.py
=> :Fixed: upgrade old domain links in theme

docs/en/theme/overrides/partials/content.html, docs/zh/theme/overrides/partials/content.html
=> :Upgrade: remove auto label add with create issue use utterances-bot

docs/zh/mkdocs.yml
=> modify redirect issue

docs/zh/mkdocs.yml
=> :update: update zh/ redirects /dce/whatisdce

docs/zh/docs/network/modules/ingress-nginx/ingressclass.md, docs/zh/navigation.yml
=> Add ingress class

docs/zh/docs/network/modules/ingress-nginx/ingressclass.md, docs/zh/navigation.yml
=> updated network ingressclass.md

docs/zh/docs/insight/09FAQs/debuglog.md, docs/zh/docs/insight/09FAQs/debugtrace.md
=> updated insight text

docs/zh/docs/ghippo/permissions/amamba.md, docs/zh/docs/ghippo/permissions/insight.md, docs/zh/navigation.yml
=> updated permissions page

docs/zh/docs/mspider/03UserGuide/01ServiceList/service-entry.md, docs/zh/docs/mspider/03UserGuide/02TrafficGovernance/VirtualService.md
感觉字段介绍部分格式不统一， 按照少数服从多数的原则稍微规范了一下格式
=> fix params 格式

docs/zh/docs/network/modules/spiderpool/install.md, docs/zh/docs/network/modules/spiderpool/usage.md
=> updated network pages

docs/zh/docs/reference/troubleshooting/ghippo02.md
=> Fixed authN troubleshooting document

docs/zh/docs/insight/03ProductBrief/releasenote.md
=> updated insight rn

docs/zh/docs/kairship/01product/release-notes.md, docs/zh/docs/kpanda/03ProductBrief/release-notes.md, docs/zh/docs/mspider/01Intro/release-notes.md, docs/zh/navigation.yml
Fix #348
Fix #366 
Fix #370
为容器管理、多云、服务网格增加了 release notes
=> added release notes for kpanda, kairship, mspider

docs/zh/docs/network/modules/f5networks/debug.md
hi, teams, A debug.md has been added to the f5networks to explain some of the problems encountered with the installation.
Signed-off-by: ty-dc [tao.yang@daocloud.io](mailto:tao.yang@daocloud.io)
=> add f5networks debug.md

docs/zh/docs/network/modules/f5networks/debug.md, docs/zh/navigation.yml
=> updated f5network debug page

docs/zh/docs/dce/kcsp.md, docs/zh/docs/download/dce.md, docs/zh/docs/download/details.md, docs/zh/navigation.yml
=> added download page

style.md
=> Added prettier in style.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, README_zh.md, style.md
=> updated readme

docs/zh/docs/blogs/kcsp.md
=> Fix format in blog

docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang.md
=> update otel guide docs

style.md
=> updated styleguide

docs/zh/docs/kpanda/03ProductBrief/release-notes.md, docs/zh/navigation.yml
=> updated kpanda release notes

docs/zh/docs/insight/03ProductBrief/releasenote.md
=> updated insight release notes

docs/zh/docs/amamba/01ProductBrief/release-notes.md, docs/zh/navigation.yml
=> updated amamba release notes

docs/zh/docs/kairship/01product/release-notes.md
=> updated kairship release notes

docs/zh/docs/skoala/intro/release-notes.md, docs/zh/navigation.yml
=> updated skoala release notes

docs/zh/docs/videos/install.md, docs/zh/navigation.yml
=> video: add videos about create clsuter and oneline install community version

docs/zh/docs/native/news.md
=> updated news of native

docs/zh/docs/native/news.md
=> updated native news page

docs/zh/docs/native/news.md
有几个问题：
1. “” 引号在 markdown 渲染的不好
2. 长句需要适当在标点符号、中英之间折行，方便 review 和修改
3. 长链接尽量隐藏，像乱码一样暴露毫无意义
=> improve readability and review of native

docs/zh/docs/ghippo/install/offlineInstall.md
=> update ghippo offlineInstall

docs/zh/docs/ghippo/install/offlineInstall.md, docs/zh/navigation.yml
=> updated ghippo offline-install

docs/zh/docs/ghippo/install/offlineInstall.md
=> update offline install

docs/zh/docs/ghippo/install/offlineInstall.md
add chart upgrade in ofline install
=> add chart upgrade in ofline install

docs/zh/docs/ghippo/install/offlineInstall.md
=> fix chart upgrade bug

docs/zh/docs/native/knowledge.md, docs/zh/docs/native/news.md, docs/zh/docs/native/open.md
=> updated native nav-level

docs/zh/docs/install/intro.md
=> updated install intro

docs/zh/docs/install/commercial/clusterconfig.md, docs/zh/docs/install/intro.md
=> added install of commercial

docs/zh/docs/install/intro.md, docs/zh/docs/native/commerce.md, docs/zh/docs/native/knowledge.md, docs/zh/docs/native/open.md
=> updated nav of native pages

docs/zh/docs/dce/what-is-dce.md
=> add portal to modules on home

docs/zh/docs/blogs/amamba.md, docs/zh/docs/blogs/index.md, docs/zh/docs/blogs/kairship.md, docs/zh/docs/blogs/kpanda.md, docs/zh/docs/blogs/mspider.md, docs/zh/navigation.yml
=> added blog index

docs/zh/docs/ghippo/install/offlineInstall.md
=> move note in upgrade

docs/zh/docs/network/modules/spiderpool/usage.md
Signed-off-by: iiiceoo <ziqian.xue@daocloud.io>
=> docs: Update Spiderpool annotations used in the Deployment manifest

docs/zh/docs/ghippo/permissions/mcamel.md, docs/zh/navigation.yml
=> Add macamel permissions in ghippo

docs/zh/docs/blogs/dce5-install1209.md, docs/zh/docs/blogs/index.md, docs/zh/docs/install/intro.md, docs/zh/navigation.yml
=> add a blog of install dce5.0

docs/zh/docs/blogs/dce5-install1209.md, docs/zh/docs/blogs/index.md, docs/zh/docs/dce/terms.md, docs/zh/navigation.yml
=> add date to blogs

poetry.lock
=> update python library to latest version

docs/zh/docs/videos/mcamel.md
Signed-off-by: Michelle Wu <michelle.wu@daocloud.io>
=> middleware: add video about redis

docs/zh/docs/ghippo/install/offlineInstall.md
=> fix space error

scripts/README.md, scripts/translate_md.py
=> update new scripts to support translate markdown

docs/en/navigation.yml
=> updated half of en-nav

docs/en/docs/dce/scenario.md, docs/en/docs/ghippo/permissions/amamba.md, docs/en/docs/ghippo/permissions/mcamel.md, docs/en/docs/ghippo/permissions/mspider.md, docs/en/docs/ghippo/permissions/skoala.md, docs/en/docs/hwameistor/application/tidb.md, docs/en/docs/insight/03ProductBrief/releasenote.md, docs/en/docs/insight/09FAQs/servicemonitor.md, docs/en/docs/kpanda/03ProductBrief/Concepts.md, docs/en/docs/kpanda/07UserGuide/Scale/Create-HPA.md, docs/en/docs/kpanda/07UserGuide/ServicesandRoutes/CreatingServices.md, docs/en/docs/kpanda/07UserGuide/Workloads/CreateCronJobByImage.md, docs/en/docs/kpanda/07UserGuide/Workloads/CreateDaemonSetByImage.md, docs/en/docs/kpanda/07UserGuide/Workloads/CreateDeploymentByImage.md, docs/en/docs/kpanda/07UserGuide/Workloads/CreateJobByImage.md, docs/en/docs/kpanda/07UserGuide/Workloads/CreateStatefulSetByImage.md, docs/en/docs/kpanda/07UserGuide/Workloads/PodConfig/SchedulingPolicy.md, docs/en/docs/kpanda/07UserGuide/Workloads/PodConfig/healthcheck.md, docs/en/docs/middleware/elastic-search/userguide/cluster-capacity-plan.md, docs/en/docs/middleware/minio/intro/concepts.md, docs/en/docs/mspider/01Intro/Scenarios.md, docs/en/docs/mspider/03UserGuide/02TrafficGovernance/VirtualService.md, docs/en/docs/mspider/03UserGuide/02TrafficGovernance/vsparams.md, docs/en/docs/mspider/03UserGuide/05Security/params.md, docs/en/docs/mspider/03UserGuide/10MeshConfiguration/IstioResources.md, docs/en/docs/native/news.md, docs/en/navigation.yml, docs/zh/docs/kpanda/07UserGuide/Scale/Create-HPA.md, docs/zh/docs/kpanda/07UserGuide/Workloads/CreateStatefulSetByImage.md
=> Add en text to some pages

docs/en/docs/dce/what-is-dce.md, docs/en/docs/index.md, docs/en/navigation.yml
=> Updated en homepage

poetry.lock, pyproject.toml, scripts/README.md
=> 📝 update translate_md usage docs

docs/en/docs/amamba/03UserGuide/Pipeline/createpipelinebyself.md, docs/en/docs/amamba/03UserGuide/Pipeline/graphicaleditingpipeline.md, docs/en/docs/index.md, docs/en/docs/kpanda/07UserGuide/CustomResources/create.md, docs/en/docs/native/open.md, docs/en/docs/videos/amamba.md, docs/en/docs/videos/ghippo.md, docs/en/docs/videos/index.md, docs/en/docs/videos/insight.md, docs/en/docs/videos/install.md, docs/en/docs/videos/kairship.md, docs/en/docs/videos/kangaroo.md, docs/en/docs/videos/kpanda.md, docs/en/docs/videos/mcamel.md, docs/en/docs/videos/mspider.md, docs/en/docs/videos/skoala.md, docs/en/theme/404.html, docs/en/theme/main.html
=> updated en text for videos

docs/en/docs/blogs/amamba.md, docs/en/docs/blogs/blog00.md, docs/en/docs/blogs/kcsp.md, docs/en/docs/dce/kcsp.md, docs/en/docs/dce/scenario.md, docs/en/docs/download/dce5.md, docs/en/docs/install/intro.md, docs/en/docs/kangaroo/intro.md, docs/en/docs/middleware/kafka/intro/what.md, docs/en/docs/middleware/minio/intro/what.md, docs/en/docs/middleware/redis/intro/what.md, docs/en/docs/mspider/01Intro/WhatismSpider.md, docs/en/docs/native/news.md, docs/en/docs/skoala/select-workspace.md, docs/en/docs/videos/network.md, docs/zh/docs/videos/network.md
=> change link at the bottom of video pages

docs/zh/docs/ghippo/install/offlineInstall.md
=> fix offline pkg install

resources/k8s/calico.yaml, resources/k8s/metrics-server.yaml
=> 📝  update resources

docs/en/docs/ghippo/04UserGuide/02Workspace/a-cluster-to-multi-ws.md, docs/en/docs/ghippo/04UserGuide/02Workspace/authu-plan.md, docs/en/docs/ghippo/04UserGuide/02Workspace/wsbp.md
=> Fix issues 645, 646, 647

docs/zh/docs/network/modules/falco-exporter/install.md, docs/zh/docs/network/modules/falco/install.md, docs/zh/docs/network/modules/falco/what.md
Signed-off-by: tao.yang <tao.yang@daocloud.io>
修改了一些格式问题。
=> fix docs for falco and falco-exporter

docs/zh/docs/kairship/01product/release-notes.md
=> 📝 update kairship release notes

docs/zh/docs/download/modules/insight.md, docs/zh/docs/insight/06UserGuide/01quickstart/offlineInstall.md
add insight offline package info
=> add insight offline info

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.3.30.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.3.30.md
download: dce5 version updated to v0.3.30
=> download: dce5 version updated to v0.3.30

docs/zh/docs/community/clusterpedia.md, docs/zh/docs/community/kubean.md, docs/zh/docs/storage/hwameistor/intro/what.md, docs/zh/docs/storage/intro.md, docs/zh/docs/storage/terms/csi.md
dce5-Installer 封装的版本需与各模块的 release-notes 建立关联
=> updated releases

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.4.0-rc2.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.4.0-rc2.md
download: dce5 version updated to v0.4.0-rc2
=> download: dce5 version updated to v0.4.0-rc2

docs/zh/docs/download/dce5.md
=> download: change version

docs/zh/docs/download/business/.dce5-installer-template.md, docs/zh/docs/download/free/.dce5-installer-template.md
=> download: modify template

docs/en/mkdocs.yml, docs/en/theme/overrides/main.html, docs/en/theme/overrides/partials/comments.html, docs/en/theme/overrides/partials/content.html, docs/zh/docs/stylesheets/custom.css, docs/zh/mkdocs.yml, docs/zh/theme/overrides/main.html, docs/zh/theme/overrides/partials/comments.html, docs/zh/theme/overrides/partials/content.html
=> 📝 upgrade comment system to giscus with Discussions

docs/zh/docs/storage/solutions/dce-longhorn.md, docs/zh/docs/storage/solutions/dce-rook-ceph.md, docs/zh/docs/storage/solutions/helm-rook-ceph.md, docs/zh/docs/storage/solutions/longhorn.md, docs/zh/docs/storage/solutions/rook-ceph.md, docs/zh/navigation.yml
=> update storage solutions

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.4.0.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.4.0.md
download: dce5 version updated to v0.4.0
=> download: dce5 version updated to v0.4.0

docs/en/docs/blogs/dce5-install1209.md, docs/en/docs/download/business/.dce5-installer-template.md, docs/en/docs/download/business/dce5-installer-v0.3.28.md, docs/en/docs/download/business/dce5-installer-v0.3.29.md, docs/en/docs/download/business/dce5-installer-v0.4.0.md, docs/en/docs/download/free/.dce5-installer-template.md, docs/en/docs/download/free/dce5-installer-v0.3.27.md, docs/en/docs/download/free/dce5-installer-v0.3.28.md, docs/en/docs/download/free/dce5-installer-v0.3.29.md, docs/en/docs/download/free/dce5-installer-v0.4.0.md, docs/en/navigation.yml, docs/zh/navigation.yml
=> update download pages

docs/zh/docs/amamba/02QuickStart/argocd-rollout.md, docs/zh/docs/blogs/dce5-install1209.md, docs/zh/docs/ghippo/04UserGuide/open-audit.md, docs/zh/docs/ghippo/gproduct/nav.md, docs/zh/docs/ghippo/gproduct/route-authn.md, docs/zh/docs/ghippo/install/offlineInstall.md, docs/zh/docs/insight/06UserGuide/01quickstart/offlineInstall.md, docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang-ebpf.md, docs/zh/docs/insight/06UserGuide/01quickstart/otel/golang.md, docs/zh/docs/insight/06UserGuide/01quickstart/otel/operator.md, docs/zh/docs/insight/06UserGuide/07collectionmanag/servicemonitor.md
- 增加 yaml 文件名（如果有）
- 将 yaml 注释文字改为折叠浮窗
=> modiy annotations in yaml

docs/zh/docs/network/modules/ingress-nginx/cors.md
=> Update cors docs

docs/zh/docs/community/index.md, docs/zh/navigation.yml
=> update community home

docs/en/docs/blogs/dce5-install1209.md, docs/zh/docs/blogs/dce5-install1209.md
=> 🐞 fix: fix blog incorrect

docs/zh/docs/videos/index.md, docs/zh/docs/videos/install.md, docs/zh/docs/videos/skoala.md, docs/zh/navigation.yml
=> updated video pages

docs/zh/docs/install/community/kind/online.md
教程里这一步需要添加chmod +x ./dce5-installer   要添加权限
=> update get kind IP

docs/zh/docs/mspider/03UserGuide/07SidecarManagement/passthrough.md
=> updated mspider passthrough

docs/zh/docs/blogs/peter.md
=> updated blog peter

docs/zh/docs/blogs/projects.md, docs/zh/navigation.yml
=> update new blog of project list

docs/en/docs/videos/insight.md, docs/zh/docs/videos/insight.md
=> add a video to insight

docs/zh/docs/insight/user-guide/system-config/modify-config.md
=> Fix commands to modify insight sys-config

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.5.0.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.5.0.md
download: dce5 version updated to v0.5.0
=> download: dce5 version updated to v0.5.0

docs/zh/docs/download/business/dce5-installer-v0.5.0.md, docs/zh/navigation.yml
=> fix download nav

docs/zh/docs/download/addon/v0.5.2.md, docs/zh/docs/download/dce5.md, docs/zh/navigation.yml
=> update addon download

docs/zh/docs/blogs/macos.md
=> fix an image of macos install

docs/zh/docs/blogs/macos.md
=> update a command of macos install

docs/zh/docs/blogs/macos.md
=> update macos install text

docs/zh/docs/blogs/macos.md
=> add usage and uninstall to mac-install

docs/en/docs/videos/ghippo.md, docs/zh/docs/videos/ghippo.md
=> add a ghippo video

docs/zh/docs/kangaroo/hosted/operator.md, docs/zh/navigation.yml
=> update kangaroo toc

docs/zh/docs/reference/template.md
=> add a sandbox template

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.6.0.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.6.0.md
download: dce5 version updated to v0.6.0
=> download: dce5 version updated to v0.6.0

docs/zh/docs/videos/amamba.md, docs/zh/docs/videos/ghippo.md, docs/zh/docs/videos/insight.md, docs/zh/docs/videos/mspider.md, docs/zh/docs/videos/skoala.md
=> add index to video pages

docs/zh/docs/mspider/user-guide/security/README.md
=> update mspider security page

docs/zh/docs/install/commercial/deploy-requirements.md
=>  add port requirements

docs/zh/docs/install/commercial/deploy-requirements.md
=> Add cilium ports and change kube to k8s

docs/zh/docs/install/commercial/deploy-requirements.md
Add kube vip port-requirements
Shorter the title
=> Add kube vip port-requirements

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.6.1.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.6.1.md
download: dce5 version updated to v0.6.1
=> download: dce5 version updated to v0.6.1

docs/zh/docs/skoala/best-practice/auth-server.md
=> update skoala authserver docs

docs/zh/docs/blogs/k8s1.27.md
=> update blog: 1.27 release

docs/zh/docs/mspider/user-guide/service-mesh/params.md
翻译为中文
```
docs/zh/docs/mspider/user-guide/service-mesh/params.md
```
=> add mspider params

docs/zh/docs/openapi/mcamel/elasticsearch-index.md, docs/zh/docs/openapi/mcamel/elasticsearch-v0.7.0.json, docs/zh/docs/openapi/mcamel/elasticsearch-v0.7.0.md
openapi: mcamel version updated to v0.7.0
=> openapi: elasticsearch version updated to v0.7.0

docs/zh/docs/openapi/mcamel/rabbitmq-index.md, docs/zh/docs/openapi/mcamel/rabbitmq-v0.10.0.json, docs/zh/docs/openapi/mcamel/rabbitmq-v0.10.0.md
openapi: mcamel version updated to v0.10.0
=> openapi: rabbitmq version updated to v0.10.0

docs/zh/docs/openapi/mcamel/postgresql-index.md, docs/zh/docs/openapi/mcamel/postgresql-v0.1.1.json, docs/zh/docs/openapi/mcamel/postgresql-v0.1.1.md
openapi: mcamel version updated to v0.1.1
=> openapi: postgresql version updated to v0.1.1

docs/zh/docs/kpanda/best-practice/update-offline-cluster.md, docs/zh/navigation.yml
=> add offline updatecluster

docs/zh/docs/network/modules/ingress-nginx/scope.md, docs/zh/docs/network/modules/spiderpool/cutomizedusage.md
update cutomizedusage.md & ingress scope.md
=> update cutomizedusage.md & ingress scope.md

.github/ISSUE_TEMPLATE/add-openapi.yml, .github/workflows/api-doc.yml
See https://github.com/kebe7jun/DaoCloud-docs/pull/6 and https://github.com/kebe7jun/DaoCloud-docs/issues/2
本地 clone 一份 docs 太慢了，经常失败，这样我们可以创建一个 issue 就可以把 OpenAPI 自动传上来了。
=> Add openapi doc workflow

docs/zh/docs/openapi/mcamel/postgresql-index.md, docs/zh/docs/openapi/mcamel/postgresql-v0.1.2.json, docs/zh/docs/openapi/mcamel/postgresql-v0.1.2.md
openapi: mcamel version updated to v0.1.2
=> openapi: postgresql version updated to v0.1.2

docs/zh/docs/openapi/mcamel/rabbitmq-index.md, docs/zh/docs/openapi/mcamel/rabbitmq-v0.10.1.json, docs/zh/docs/openapi/mcamel/rabbitmq-v0.10.1.md
openapi: mcamel version updated to v0.10.1
=> openapi: rabbitmq version updated to v0.10.1

docs/zh/docs/openapi/mcamel/elasticsearch-index.md, docs/zh/docs/openapi/mcamel/elasticsearch-v0.7.1.json, docs/zh/docs/openapi/mcamel/elasticsearch-v0.7.1.md
openapi: mcamel version updated to v0.7.1
=> openapi: elasticsearch version updated to v0.7.1

docs/zh/docs/openapi/index.md, docs/zh/docs/openapi/midware.md
尝试美化 2 个页面：
- openapi index
- midware index
=> beautify openapi index

.github/workflows/main.yml, scripts/docs/merge_nav.md, scripts/merge_nav.py
=> Another way to update the openapi docs

docs/zh/docs/dce/what.md
=> Fix the typo pic url.

docs/en/docs/install/community/kind/online.md, docs/zh/docs/install/community/kind/online.md
Make kind_cluster.yaml containerPort default=32088
=> kind_cluster.yaml containerPort default=32088

docs/zh/docs/blogs/230509-k8s-install.md, docs/zh/docs/blogs/index.md, docs/zh/navigation.yml
=> add a blog: install k8s

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.7.0.md, docs/zh/docs/download/dce5.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.7.0.md
download: dce5 version updated to v0.7.0
=> download: dce5 version updated to v0.7.0

docs/zh/docs/blogs/230509-k8s-install.md, docs/zh/docs/install/commercial/cluster-config.md, docs/zh/docs/install/commercial/deploy-requirements.md, docs/zh/docs/install/commercial/start-install.md, docs/zh/docs/install/community/k8s/offline.md, docs/zh/docs/install/faq.md, docs/zh/docs/install/os-install/otherlinux.md, docs/zh/docs/install/release-notes.md, docs/zh/navigation.yml
=> update download and install

docs/en/docs/install/uninstall.md, docs/zh/docs/install/uninstall.md
* Fix syntax of Community Package
* Remove useless namespaces after uninstall
=> fix: improve uninstall syntax and remove useless namespaces

docs/en/docs/network/modules/ingress-nginx/what.md, docs/en/docs/network/modules/modules.md, docs/zh/docs/network/modules/modules.md
1 修复外链错误
2 修复ingress-nginx的英文引导页面
=> 修复Ingress-nginx文档

docs/en/docs/install/commercial/deploy-arch.md, docs/en/docs/install/commercial/prepare.md, docs/en/docs/install/commercial/scenarios.md, docs/en/docs/install/commercial/start-install.md, docs/en/docs/install/intro.md, docs/zh/docs/install/intro.md
=> update install intro

docs/zh/docs/mspider/intro/release-notes.md
=> mspider: update release note

docs/zh/docs/community/index.md, docs/zh/docs/community/kwok.md, docs/zh/docs/community/spiderpool.md, docs/zh/docs/dce/scenario.md, docs/zh/docs/ghippo/gproduct/intro.md, docs/zh/docs/kairship/intro/what.md, docs/zh/docs/mspider/intro/scenarios.md, docs/zh/docs/network/modules/spiderpool/what.md, docs/zh/docs/skoala/intro/scenarios.md
- 场景化视频增加到更多页面
- spiderpool 入选 CNCF 后的相关更新
=> add videos to scenarios page and update spiderpool

docs/zh/docs/insight/faq/service-monitor.md
Fix https://github.com/DaoCloud/DaoCloud-docs/discussions/1459
=> update servicemitor yaml

docs/zh/docs/kangaroo/release-notes.md
add kangaroo June release note
=> add kangaroo release note

docs/zh/docs/community/spiderpool.md, docs/zh/docs/dce/scenario.md, docs/zh/docs/ghippo/gproduct/intro.md, docs/zh/docs/kairship/intro/what.md, docs/zh/docs/kpanda/best-practice/backup-mysql-on-nfs.md, docs/zh/docs/mspider/intro/scenarios.md, docs/zh/docs/network/modules/spiderpool/what.md, docs/zh/docs/skoala/intro/scenarios.md
发现文档页加了视频后，页面显示不正常，先删除吧：
https://docs.daocloud.io/mspider/intro/scenarios/
=> replace videos with links on doc pages

docs/en/docs/amamba/quickstart/scan-with-harbor.md, docs/en/docs/amamba/quickstart/scan-with-pipeline.md, docs/en/docs/blogs/230214-open-projects.md, docs/en/docs/blogs/230315-install-on-linux.md, docs/en/docs/blogs/230315-install-on-macos.md, docs/en/docs/blogs/230405-step-by-step-dce5.md, docs/en/docs/blogs/230412-k8s-1.27.md, docs/en/docs/blogs/index.md, docs/en/docs/download/business/dce5-installer-v0.8.0.md, docs/en/docs/install/commercial/start-install.md, docs/en/docs/install/community/k8s/offline.md, docs/en/docs/install/community/kind/online.md, docs/en/docs/install/install-tools.md, docs/en/docs/install/intro.md, docs/en/docs/install/os-install/oracleLinux-install-dce5.0.md, docs/en/docs/install/os-install/otherlinux.md, docs/en/docs/install/release-notes.md, docs/en/docs/middleware/elasticsearch/faq/common-question-es.md, docs/en/docs/middleware/mysql/faq/common-question.md, docs/en/docs/native/commerce.md, docs/en/navigation.yml, docs/zh/docs/install/commercial/start-install.md, docs/zh/navigation.yml
- Sync with install pages
- Keep terms consistent: Community Package, Enterprise Package
=> update en install pages

.github/labeler.yml
=> update label list

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.8.0-rc2.md, docs/zh/docs/download/dce5.md
download: addon version updated to v0.8.0-rc2
=> download: addon version updated to v0.8.0-rc2

docs/zh/docs/download/modules/gmagpie.md
add gmagpie offline install page
=> add gmagpie offline install page 

style.md
=> updated style.md

docs/zh/docs/download/modules/gmagpie.md
download: gmagpie version updated to v0.3.0
=> download: gmagpie version updated to v0.3.0

docs/en/navigation.yml, docs/zh/navigation.yml
revert one-click download package
=> update nav about installation

docs/en/docs/network/modules/spiderpool/createpool.md, docs/en/docs/network/modules/spiderpool/cutomizedusage.md, docs/en/docs/network/modules/spiderpool/ippoolusage.md, docs/en/docs/network/modules/spiderpool/usage.md, docs/en/docs/network/modules/spiderpool/what.md, docs/en/docs/network/plans/ethplan.md, docs/zh/docs/network/modules/spiderpool/createpool.md, docs/zh/docs/network/modules/spiderpool/cutomizedusage.md, docs/zh/docs/network/modules/spiderpool/ippoolusage.md, docs/zh/docs/network/modules/spiderpool/usage.md, docs/zh/docs/network/modules/spiderpool/what.md, docs/zh/docs/network/plans/ethplan.md, docs/zh/docs/network/plans/netplan.md
=> fix term sr-iov

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.9.0.md, docs/zh/docs/download/dce5.md
download: addon version updated to v0.9.0
=> download: addon version updated to v0.9.0

docs/en/navigation.yml, docs/zh/navigation.yml
=> change the channel sequence

docs/zh/docs/ghippo/user-guide/audit/open-audit.md
add note about open audit in kind
=> add note about open audit in kind

docs/en/docs/kant/intro/join-rqmt.md, docs/zh/docs/kant/intro/join-rqmt.md
=> update kant join-rqmt

docs/zh/docs/ghippo/install/offline-install.md
=> fix offline install

docs/zh/docs/storage/hwameistor/install/deploy-operator.md, docs/zh/docs/storage/hwameistor/install/drbdinstall.md, docs/zh/docs/storage/hwameistor/resources/disk_nodes.md, docs/zh/docs/storage/hwameistor/resources/lvm_nodes.md, docs/zh/docs/storage/hwameistor/resources/volume-ProvisionedIO.md, docs/zh/navigation.yml
update node-expansion & Volume IO docs
=> update node-expansion & Volume IO docs

docs/zh/docs/amamba/user-guide/pipeline/template/info.md
添加了 amamba 文档里面关于 jenkinsfileTemplate 一节的说明，优化了 parameterDefinitions 的描述
=> fix: add jenkinsfileTemplate intro

docs/zh/docs/download/modules/kpanda.md
download: kpanda version updated to 0.20.0+dev-2f4f4368
=> download: kpanda version updated to 0.20.0+dev-2f4f4368

CODEOWNERS
Clearly show the owner of the ghippo documents
=> update ghippo owner

docs/zh/docs/videos/amamba.md, docs/zh/docs/videos/ghippo.md, docs/zh/docs/videos/insight.md, docs/zh/docs/videos/kpanda.md
为 design 提供方便，让 video 结构与产品目录保持一致
=> update structure in video-home

docs/zh/docs/download/modules/gmagpie.md
download: gmagpie version updated to v0.3.2
=> download: gmagpie version updated to v0.3.2

docs/zh/docs/install/community/k8s/offline.md, docs/zh/docs/install/community/k8s/online.md, docs/zh/docs/install/community/kind/online.md, docs/zh/navigation.yml
与[体验社区版](https://docs.daocloud.io/trial/)页面的表述保持一致。
=> update all-in-one install by following trial channel

docs/en/docs/download/index.md, docs/en/docs/download/modules/insight.md, docs/zh/docs/download/index.md, docs/zh/docs/download/modules/insight.md
Manually update with #2046 before the script is changed
=> update download insight to v0.19.1

docs/zh/docs/network/intro/releasenotes.md
update spiderpool release notes
=> update spiderpool release notes

docs/zh/docs/network/performance/cni-performance.md
fix some links mentioned in #2083
=> fix zh links for network

docs/zh/docs/install/upgrade.md
=> 修改clusterConfig.yaml文件名错误

docs/en/docs/install/upgrade.md
=> fix clusterConfig.yaml in en version

docs/en/docs/kangaroo/faq.md, docs/en/docs/kangaroo/quickstart/trivy-offline.md, docs/en/navigation.yml, docs/zh/docs/kangaroo/quickstart/trivy-offline.md
=> add en offline scan

docs/en/docs/mspider/best-practice/use-custom-workloads.md, docs/en/navigation.yml, docs/zh/docs/mspider/best-practice/use-custom-workloads.md, docs/zh/navigation.yml
=> add en custom workloads to mspider

docs/zh/docs/install/community/kind/online.md
fix test shell script. need review
=> Update online.md, need review

docs/en/docs/install/community/kind/online.md
=> update en online kind-install

docs/zh/docs/network/modules/metallb/index.md, docs/zh/docs/network/modules/metallb/source_ip.md, docs/zh/docs/network/modules/metallb/usage.md
=> update metalb docs

docs/en/docs/dce/license0.md, docs/en/docs/trial/index.md, docs/en/navigation.yml, docs/zh/navigation.yml
- 缩短了左侧导航栏 blog 标题名
- 更新了 en license 页面
=> Use shorter titles in nav to be shown in a row

docs/zh/docs/network/modules/spiderpool/publiccloud.md
spiderpool 开源项目中该文档已更新，同步更新文档站的内容。
=> update spiderpool docs

docs/en/docs/network/modules/spiderpool/alibabacloud.md, docs/zh/docs/network/modules/spiderpool/alibabacloud.md
Update the en docs of spiderpool
=> Update the en docs of spiderpool

docs/zh/docs/download/modules/dowl.md, docs/zh/navigation.yml
add dowl offline download template
=> add dowl offline download template

docs/en/mkdocs.yml, docs/zh/mkdocs.yml
halt processing when a warning is raised
=> enable strict mode

docs/zh/docs/ghippo/install/gmagpie-offline-install.md, docs/zh/navigation.yml
=> add gmagpie offline doc

.github/workflows/main.yml
=> fix: build error

docs/en/mkdocs.yml, docs/zh/mkdocs.yml
=> fix: build error again

docs/en/docs/insight/user-guide/data-query/trace.md
=> update en trace query

docs/zh/docs/download/modules/amamba.md
download: amamba version updated to 0.19.5
=> download: amamba version updated to 0.19.5

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/mspider.md
download: mspider version updated to v0.19.0
=> download: mspider version updated to v0.19.0

docs/zh/docs/mspider/intro/release-notes.md
=> mspider: Add a new release for v0.19.0

docs/zh/docs/download/modules/kairship.md
download: kairship version updated to v0.12.0
=> download: kairship version updated to v0.12.0

docs/zh/docs/download/modules/kcoral.md
download: kcoral version updated to v0.5.0
=> download: kcoral version updated to v0.5.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/kangaroo.md
download: kangaroo version updated to 0.11.0
=> download: kangaroo version updated to 0.11.0

docs/zh/docs/dce/dce-rn/20230731.md
新增 2 个link，可以直接下载导出的 word 和 pdf
=> add download link to exported word and pdf

docs/zh/docs/download/modules/gmagpie.md
update gmagpie offline install
=> update gmagpie offline install

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.11.0.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.11.0.md, docs/zh/docs/download/index.md
download: dce5 version updated to v0.11.0
=> download: dce5 version updated to v0.11.0

docs/zh/docs/download/modules/dowl.md
download: dowl version updated to v0.5.1
=> download: dowl version updated to v0.5.1

docs/zh/docs/download/index.md
=> Add an intro pdf to DCE 5.0

docs/zh/docs/amamba/quickstart/jenkins-HA.md, docs/zh/navigation.yml
=> docs: add jenkins ha

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/kpanda.md
download: kpanda version updated to 0.21.1
=> download: kpanda version updated to 0.21.1

docs/zh/docs/network/modules/aliyun-terway/index.md, docs/zh/docs/network/modules/multus-underlay/index.md, docs/zh/docs/network/modules/multus-underlay/install.md
docs: mark multus-underlay to deprecated state
=> docs: mark multus-underlay to deprecated state

docs/en/docs/download/index.md, docs/en/docs/download/modules/kant.md, docs/en/docs/kant/intro/release-notes.md, docs/en/navigation.yml, docs/zh/docs/download/index.md, docs/zh/docs/download/modules/kant.md, docs/zh/docs/kant/intro/release-notes.md, docs/zh/navigation.yml
add kant download pages，releasenote content will be updated later.
=> Add kant download pages

docs/zh/docs/kpanda/intro/index.md
This is a trial to refractor the home page of each module:
- Remove redundant features list
- Add grid cards and links to each procedure page
=> Update kpanda homepage

docs/en/docs/ghippo/user-guide/access-control/webhook.md, docs/en/docs/kangaroo/best-practice/managed-harbor-select-access-type.md, docs/en/navigation.yml, docs/zh/docs/ghippo/user-guide/access-control/webhook.md, docs/zh/docs/kangaroo/best-practice/managed-harbor-select-access-type.md, docs/zh/navigation.yml
=> update webhook location and nav

docs/en/docs/mspider/troubleshoot/dce4.0-issues.md, docs/en/docs/mspider/troubleshoot/index.md, docs/zh/docs/mspider/troubleshoot/dce4.0-issues.md, docs/zh/docs/mspider/troubleshoot/index.md
=> update troubleshoot doc, when Istio Hosting in DCE4

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.10.0.md, docs/zh/docs/download/index.md
download: addon version updated to v0.10.0
=> download: addon version updated to v0.10.0

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.11.0.md, docs/zh/docs/download/index.md
download: addon version updated to v0.11.0
=> download: addon version updated to v0.11.0

docs/zh/navigation.yml
Try to keep doc nav consistent with our product UI:
=> update nav by following ui

docs/zh/navigation.yml
[docs]: Add spiderpool and sriov to navigation.yml
=> [docs]: Add spiderpool and sriov to navigation.yml

docs/zh/docs/network/modules/aliyun-terway/Q_A.md, docs/zh/docs/network/modules/aliyun-terway/aliyun-calico.md, docs/zh/docs/network/modules/aliyun-terway/index.md, docs/zh/docs/network/modules/aliyun-terway/usage.md
docs: run calico and cilium in aliyun
=> [WIP]docs: run calico and cilium in aliyun

docs/zh/navigation.yml
- 把以下 4 个模块移到了 kpanda 目录：
- 云原生网络
- 云原生存储
- 虚拟机容器
- 云原生安全
- 将 insight 与容器、微服务等并列
=> Update zh nav

README.md, README_zh.md
=> update readme with kcsp content

docs/en/docs/dce/get-started.md, docs/en/navigation.yml
=> Update en nav and get-started

docs/zh/docs/download/modules/middleware/elasticsearch.md, docs/zh/docs/download/modules/middleware/kafka.md, docs/zh/docs/download/modules/middleware/minio.md, docs/zh/docs/download/modules/middleware/mongodb.md, docs/zh/docs/download/modules/middleware/mysql.md, docs/zh/docs/download/modules/middleware/postgresql.md, docs/zh/docs/download/modules/middleware/rabbitmq.md, docs/zh/docs/download/modules/middleware/redis.md, docs/zh/navigation.yml
=> update middleware download template

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/minio.md
download: minio version updated to v0.8.1
=> download: minio version updated to v0.8.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/mysql.md
download: mysql version updated to v0.11.1
=> download: mysql version updated to v0.11.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/elasticsearch.md
download: elasticsearch version updated to v0.10.1
=> download: elasticsearch version updated to v0.10.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/mongodb.md
download: mongodb version updated to v0.3.1
=> download: mongodb version updated to v0.3.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/kafka.md
download: kafka version updated to v0.8.1
=> download: kafka version updated to v0.8.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/redis.md
download: redis version updated to v0.11.1
=> download: redis version updated to v0.11.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/postgresql.md
download: postgresql version updated to v0.5.1
=> download: postgresql version updated to v0.5.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/mspider.md
download: mspider version updated to v0.20.0
=> download: mspider version updated to v0.20.0

docs/en/mkdocs.yml, docs/zh/mkdocs.yml
=> fix: mkdocs-metrial remove emoji resource

.github/workflows/pull-request-test.yaml
=> remove: pull request test without strict

docs/zh/docs/network/config/multus-cr.md, docs/zh/docs/network/modules/spiderpool/usage.md
=> update multus cr

CODEOWNERS
Sorry to spam. Remove from the code owner file.
=> update code owners

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/elasticsearch.md, docs/zh/docs/download/modules/middleware/kafka.md, docs/zh/docs/download/modules/middleware/minio.md, docs/zh/docs/download/modules/middleware/mongodb.md, docs/zh/docs/download/modules/middleware/mysql.md, docs/zh/docs/download/modules/middleware/postgresql.md, docs/zh/docs/download/modules/middleware/rabbitmq.md, docs/zh/docs/download/modules/middleware/redis.md
- 修正用charts-syncer无法将离线包里的chart和镜像推送到新仓库的问题
- 校验完整性命令的修正
=> fix chart name not right

README_zh.md, scripts/generate_pdf.md, scripts/generate_pdf_zh.md
=> Add en version to pdf-generating-guide

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/virtnest.md, docs/zh/docs/virtnest/install/offline-install.md, docs/zh/navigation.yml
=> add virtnest download

docs/en/docs/amamba/offline-upgrade.md, docs/en/docs/ghippo/install/offline-install.md, docs/en/docs/ghippo/user-guide/report-billing/gmagpie-offline-install.md, docs/en/docs/insight/quickstart/install/offline-install.md, docs/en/docs/kairship/intro/offline-upgrade.md, docs/en/docs/kangaroo/intro/upgrade.md, docs/en/docs/kpanda/intro/offline-upgrade.md, docs/en/docs/kpanda/user-guide/backup/offline-upgrade.md, docs/en/docs/kpanda/user-guide/inspect/offline-upgrade.md, docs/en/docs/kpanda/user-guide/security/offline-upgrade-dowl.md, docs/en/docs/network/intro/offline.md, docs/en/docs/skoala/quickstart/offline-upgrade.md, docs/zh/docs/amamba/offline-upgrade.md, docs/zh/docs/ghippo/install/offline-install.md, docs/zh/docs/ghippo/user-guide/report-billing/gmagpie-offline-install.md, docs/zh/docs/insight/quickstart/install/offline-install.md, docs/zh/docs/install/release-notes.md, docs/zh/docs/kairship/intro/offline-upgrade.md, docs/zh/docs/kangaroo/intro/upgrade.md, docs/zh/docs/kant/intro/offline-upgrade.md, docs/zh/docs/kpanda/intro/offline-upgrade.md, docs/zh/docs/kpanda/user-guide/backup/offline-upgrade.md, docs/zh/docs/kpanda/user-guide/inspect/offline-upgrade.md, docs/zh/docs/kpanda/user-guide/security/offline-upgrade-dowl.md, docs/zh/docs/middleware/minio/user-guide/offline-install.md, docs/zh/docs/network/intro/offline.md, docs/zh/docs/skoala/quickstart/offline-upgrade.md, docs/zh/docs/virtnest/install/offline-install.md
1、修复了ctr导入镜像未添加-n k8s.io的错误
2、修复了缩进错误
3、修改+号展示注释为直接展示注释
4、修复了helm拼写错误
=> fix offline docs

docs/zh/docs/virtnest/install/offline-install.md
=> fix virtnest offline install

docs/en/docs/kangaroo/intro/upgrade.md, docs/zh/docs/kangaroo/intro/upgrade.md
=> update kangaroo offline upgrade

docs/zh/docs/download/modules/kcoral.md
download: kcoral version updated to v0.6.0
=> download: kcoral version updated to v0.6.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/skoala.md
download: skoala version updated to v0.28.0
=> download: skoala version updated to v0.28.0

docs/zh/docs/download/modules/kant.md
download: kant version updated to 0.5.0
=> download: kant version updated to 0.5.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/kangaroo.md
download: kangaroo version updated to 0.12.0
=> download: kangaroo version updated to 0.12.0

docs/en/docs/mspider/user-guide/security/params.md, docs/zh/docs/mspider/user-guide/security/params.md
=> mspider: add authorizedpolicy precautions

docs/en/docs/mspider/install/offline-upgrade.md, docs/en/navigation.yml, docs/zh/docs/mspider/install/offline-upgrade.md, docs/zh/navigation.yml
=> mspider: upgrade service mesh module

docs/zh/docs/network/modules/cilium/cilium_chaining.md, docs/zh/navigation.yml
docs: support network-policy for ipvlan with cilium-chaining
=> docs: support network-policy for ipvlan with cilium-chaining

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/skoala.md
download: skoala version updated to v0.28.1
=> download: skoala version updated to v0.28.1

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/mongodb.md
download: mongodb version updated to v0.4.0
=> download: mongodb version updated to v0.4.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/mysql.md
download: mysql version updated to v0.12.0
=> download: mysql version updated to v0.12.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/rabbitmq.md
download: rabbitmq version updated to v0.14.0
=> download: rabbitmq version updated to v0.14.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/minio.md
download: minio version updated to v0.9.0
=> download: minio version updated to v0.9.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/elasticsearch.md
download: elasticsearch version updated to v0.11.0
=> download: elasticsearch version updated to v0.11.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/postgresql.md
download: postgresql version updated to v0.6.0
=> download: postgresql version updated to v0.6.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/kafka.md
download: kafka version updated to v0.9.0
=> download: kafka version updated to v0.9.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/rocketmq.md
=> add rocketmq in middleware

docs/zh/docs/download/index.md
download: rocketmq version updated to v0.1.1
=> download: rocketmq version updated to v0.1.1

docs/zh/docs/download/modules/dowl.md
download: dowl version updated to v0.6.0
=> download: dowl version updated to v0.6.0

docs/zh/docs/kant/user-guide/edge-app/create-app.md, docs/zh/docs/kant/user-guide/edge-app/create-batch-app.md
=> update kant content

docs/zh/docs/insight/intro/releasenote.md, docs/zh/docs/insight/quickstart/install/knownissues.md
=> update insight release note

docs/en/docs/insight/intro/releasenote.md, docs/en/docs/insight/quickstart/install/knownissues.md, docs/en/navigation.yml, docs/zh/docs/insight/intro/releasenote.md, docs/zh/docs/insight/quickstart/install/knownissues.md, docs/zh/navigation.yml
=> [en] translate known-issues and release-notes

docs/zh/docs/network/modules/ingress-nginx/scope.md
update ingress 'workspace scope part'
=> update ingress 'workspace scope part'

docs/zh/docs/download/modules/virtnest.md
download: virtnest version updated to v0.3.0
=> download: virtnest version updated to v0.3.0

docs/en/docs/install/commercial/start-install.md, docs/en/docs/install/community/k8s/offline.md, docs/en/docs/install/community/k8s/online.md, docs/en/docs/install/community/kind/online.md, docs/en/docs/install/k8s-install/ecs-install-dce5.0.md, docs/en/docs/install/k8s-install/ocp-install-dce5.0.md, docs/en/docs/install/release-notes.md, docs/zh/docs/install/commercial/start-install.md, docs/zh/docs/install/community/kind/online.md, docs/zh/docs/install/k8s-install/ocp-install-dce5.0.md
=> [en] update installer to v0.12.0

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/middleware/redis.md
=> download: redis version updated to v0.12.0

docs/en/docs/amamba/faq/faq-jenkins.md, docs/zh/docs/amamba/faq/faq-jenkins.md
=> update pipeline issues

docs/en/docs/kpanda/best-practice/hardening-cluster.md, docs/zh/docs/kpanda/best-practice/hardening-cluster.md
=> Fix typo of cibenchmark

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.12.0.md, docs/zh/docs/download/index.md
download: addon version updated to v0.12.0
=> download: addon version updated to v0.12.0

docs/zh/docs/dce/dce-rn/20231031.md
20231031 release notes 中新增一个 word 下载链接
=> add a v0.12.0 docx file to download

docs/en/docs/mspider/user-guide/gateway-instance/gateway-in-external-mesh.md, docs/en/navigation.yml, docs/zh/docs/mspider/user-guide/gateway-instance/gateway-in-external-mesh.md, docs/zh/navigation.yml
=> mspider: add docs: Gateway Management for External Mesh

docs/en/docs/amamba/pluggable-components.md, docs/zh/docs/amamba/pluggable-components.md
1. argocd name from `argo-cd` to `argocd`
2. argocd namespace from `argocd-system` to `argocd`
=> Update name and namespace of argocd

docs/zh/docs/kpanda/user-guide/gpu/Ascend_usage.md
=> update gpu Ascend docs

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/skoala.md
download: skoala version updated to v0.29.0
=> download: skoala version updated to v0.29.0

docs/zh/docs/network/modules/submariner/usage.md
=> Optimize submariner docs.

docs/zh/docs/network/modules/spiderpool/usage.md
=> Optimize spiderpool docs.

docs/zh/docs/network/modules/multus-underlay/macvlan.md
=> Optimize multus-underlay docs.

docs/zh/docs/network/intro/index.md
=> Optimize intro/index.md docs.

docs/zh/docs/insight/quickstart/install/upgrade-note.md
经过讨论，insight 放弃引入这个 Breakingchange
=> revert PR 2866

docs/zh/docs/ghippo/intro/faq.md, docs/zh/navigation.yml
=> add ghippo faq

.github/workflows/main.path.yml, .github/workflows/main.yml
=> workflow: add concurrency config

docs/zh/docs/download/modules/virtnest.md
download: virtnest version updated to v0.4.0
=> download: virtnest version updated to v0.4.0

docs/zh/docs/insight/quickstart/otel/operator.md
=> fix style  in otel/operator.md

docs/zh/docs/download/index.md, docs/zh/docs/download/modules/insight.md
download: insight version updated to v0.22.0
=> download: insight version updated to v0.22.0

docs/en/navigation.yml, docs/zh/docs/middleware/elasticsearch/user-guide/logs.md, docs/zh/docs/middleware/kafka/user-guide/logs.md, docs/zh/docs/middleware/mongodb/user-guide/delete.md, docs/zh/docs/middleware/mongodb/user-guide/logs.md, docs/zh/docs/middleware/mysql/user-guide/logs.md, docs/zh/docs/middleware/postgresql/user-guide/logs.md, docs/zh/docs/middleware/rabbitmq/user-guide/logs.md, docs/zh/docs/middleware/redis/user-guide/logs.md, docs/zh/navigation.yml
=> Fix typos about mongodb

docs/zh/docs/kpanda/user-guide/gpu/nvidia/push_image_to_repo.md
modify Chinese expression and fix typos
=> fix typos in push_image_to_repo

docs/en/docs/blogs/230405-step-by-step-dce5.md, docs/en/docs/download/business/dce5-installer-history.md, docs/en/docs/download/business/dce5-installer-v0.13.0.md, docs/en/docs/download/free/dce5-installer-history.md, docs/en/docs/download/free/dce5-installer-v0.13.0.md, docs/en/docs/download/index.md, docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.13.0.md, docs/zh/docs/download/free/dce5-installer-history.md
=> [en] Update installer-download to v0.13.0

docs/zh/navigation.yml
=> fix terminology about ocp

docs/en/docs/virtnest/quick-start/index.md
modify English expressions and replace VM container with VM
=> update VM expression

docs/en/docs/kant/intro/concepts.md
=> upgrade concepts dosc 

docs/en/docs/dce/dce-rn/20231130.md
=> [en] Add release notes dce-20231130

docs/zh/docs/kant/user-guide/edge-network/deploy-edgemesh.md, docs/zh/docs/kpanda/user-guide/clusters/integrate-rancher-cluster.md
更新内容：
1. kant 部署 edgemesh;
2. kpanda 接入 rancher 集群部分描述。
=> update kant & kpanda user guide

docs/zh/docs/ghippo/user-guide/audit/source-ip.md
=> add note source ip

docs/zh/docs/kant/user-guide/node/managed-node.md
=> fix  pause images

docs/en/docs/kpanda/user-guide/scale/install-metrics-server.md, docs/zh/docs/kpanda/user-guide/scale/install-metrics-server.md
=> [zh] Update two pages for kpanda

docs/en/docs/storage/hwameistor/resources/expand.md
=> fix code styles

docs/en/docs/storage/hwameistor/resources/storagepool.md, docs/zh/docs/storage/hwameistor/resources/storagepool.md
=> update hwameistor codes

docs/en/docs/storage/hwameistor/install/post-check.md, docs/zh/docs/storage/hwameistor/install/post-check.md
=> modify HwameiStor expressions

docs/zh/docs/middleware/mysql/faq/faq-master-slave.md
=> mysql: 优化命令行方便复制

docs/en/docs/kangaroo/quickstart/push.md, docs/zh/docs/kangaroo/quickstart/push.md
=> update kangaroo-quickstart codes

docs/en/docs/kangaroo/intro/index.md
=> fix kangaroo-intro typos

docs/zh/docs/download/modules/amamba.md
download: amamba version updated to v0.22.0
=> download: amamba version updated to v0.22.0

docs/en/docs/insight/quickstart/install/offline-install.md, docs/zh/docs/insight/quickstart/install/offline-install.md
update auth username/password in load-image.yaml
=> update auth username/password

docs/en/navigation.yml
Modify the parts that do not correspond to Chinese
related to #3254
=> [en] move the navigation bar structure

docs/en/docs/insight/quickstart/other/install-agentindce.md
=> update insight-install-agentindce contents

docs/en/docs/mspider/install/sidecar-update.md
=> modify mspider-sidecar-update expressions

docs/zh/docs/download/modules/amamba.md
download: amamba version updated to v0.22.1
=> download: amamba version updated to v0.22.1

docs/zh/docs/download/modules/spidernet.md
download: spidernet version updated to v0.12.0
=> download: spidernet version updated to v0.12.0

docs/zh/docs/network/modules/spiderpool/rdmapara.md, docs/zh/docs/network/modules/spiderpool/userdma.md
Fix some issues found in #3325
=> Update rdmapara.md and userdma.md to replace #3325

docs/zh/docs/middleware/elasticsearch/user-guide/create.md
=> fix image format

docs/zh/docs/middleware/index.md
=> add rocketmq intro in index

docs/en/docs/middleware/mongodb/release-notes.md, docs/zh/docs/middleware/mongodb/release-notes.md
=> fix wrong words

docs/en/docs/insight/best-practice/integration_deepflow.md, docs/en/navigation.yml, docs/zh/docs/insight/best-practice/integration_deepflow.md, docs/zh/docs/mspider/troubleshoot/cluster-interconnect.md, docs/zh/navigation.yml
=> Add a practice to Integrate deepflow with insight

docs/zh/docs/network/modules/spiderpool/userdma.md
=> update userdma usage

docs/zh/docs/network/modules/spiderpool/userdma.md
=> update rdma_usage style

docs/zh/docs/download/modules/kcoral.md
download: kcoral version updated to v0.8.0
=> download: kcoral version updated to v0.8.0

docs/en/docs/storage/hwameistor/resources/migrate.md, docs/zh/docs/storage/hwameistor/resources/migrate.md
=> update hwameistor-migrate yaml

docs/en/docs/insight/quickstart/install/offline-install.md, docs/zh/docs/insight/quickstart/install/offline-install.md
=> Update offline-install for insight

docs/zh/docs/download/modules/virtnest.md
download: virtnest version updated to v0.5.1
=> download: virtnest version updated to v0.5.1

docs/en/docs/insight/intro/releasenote.md, docs/zh/docs/insight/intro/releasenote.md
=> [en] Update insight release notes

docs/zh/docs/install/commercial/start-install.md
fix  dce5 v0.14 os-pkgs v0.11 url
=> fix  dce5 v0.14 os-pkgs v0.11 url

docs/en/docs/kpanda/user-guide/clusters/cluster-version.md, docs/en/docs/kpanda/user-guide/clusters/create-cluster.md, docs/zh/docs/kpanda/user-guide/clusters/cluster-version.md, docs/zh/docs/kpanda/user-guide/clusters/create-cluster.md
See preview: https://deploy-preview-3480--daocloud-docs.netlify.app/en/kpanda/user-guide/clusters/cluster-version
=> [en] Update supported k8s versions

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.14.0.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.14.0.md, docs/zh/docs/download/index.md
download: dce5 version updated to v0.14.0
=> download: dce5 version updated to v0.14.0

docs/en/docs/kpanda/user-guide/helm/multi-archi-helm.md, docs/en/navigation.yml, docs/zh/docs/kpanda/user-guide/helm/multi-archi-helm.md
=> Fix command in multi-archi-heml for kpanda

scripts/report_monthly.py
The document includes the following fields: Date, Author, Title, Labels, Label Count, Changed Files, Additions, Deletions, and PR Link.
=> add monthly PR statistics tool

docs/zh/docs/amamba/quickstart/scenarios-config.md
=> add amamba-scenarios-config images

docs/en/docs/install/community/k8s/offline.md
=> correct install-offline indentation

docs/en/docs/amamba/faq/faq-jenkins.md
=> add amamba-pipeline-issues docs

docs/en/docs/install/commercial/cluster-config.md, docs/en/docs/install/commercial/start-install.md
=> [en] Update cluster-config and start-install

docs/en/docs/insight/intro/features.md
=> modify insight-intro-features tables

docs/en/docs/kant/user-guide/node/managed-node.md
=> sync kant-managed-node docs

docs/en/docs/insight/intro/features.md
=> [en] update insight features

docs/zh/docs/kangaroo/best-practice/insecure_registry.md
=> fix kangaroo-insecure-registry typos

docs/en/docs/mspider/user-guide/service-list/diagnose.md
=> fix mspider-servicelist-diagnose typos

docs/en/docs/storage/hwameistor/intro/index.md
=> fix hwameistor-index typos

docs/en/navigation.yml, docs/zh/navigation.yml
=> modify hwameistor-yaml

docs/en/docs/kpanda/best-practice/add-worker-node-on-global.md, docs/zh/docs/kpanda/best-practice/add-worker-node-on-global.md
=>  modify kpanda YAML format

docs/en/docs/network/modules/spiderpool/install/install.md, docs/en/docs/network/modules/spiderpool/install/ofed_driver.md, docs/en/navigation.yml, docs/zh/navigation.yml
=> [en] Add install-nvidia-ofed-driver

docs/zh/docs/storage/hwameistor/intro/drdb-kernel-make.md, docs/zh/navigation.yml
=> add hwamei drdb kernel make

docs/en/docs/mspider/intro/features.md
=> fix: issue 3715

docs/en/docs/mspider/intro/comp-archi-ui/namespaces.md, docs/zh/docs/mspider/intro/comp-archi-ui/namespaces.md
=> fix: issue 3717

.github/workflows/auto-size-pr.yaml
=> feat: support auto pr size label

docs/en/docs/mspider/intro/index.md, docs/zh/docs/mspider/intro/index.md
=> fix: issue 3713

docs/en/docs/install/faq.md
=> Fix #3670 for installer

docs/zh/docs/network/modules/kdoctor/install.md
=> Fix kdoctor format

docs/en/docs/install/evolve.md
=> Fix #3669 in evolve.md for hwameistor

docs/en/docs/install/commercial/cluster-config.md
=> Fix #3668 in clusterconfig.md

docs/en/docs/install/install-tools.md
=> Fix #3667 about a command in install-tools.md

docs/zh/docs/native/knowledge/git/index.md
=> add url changes skills

docs/en/docs/blogs/230405-step-by-step-dce5.md, docs/en/docs/install/community/k8s/k8s-dce-deploy.md, docs/zh/docs/blogs/230405-step-by-step-dce5.md, docs/zh/docs/install/community/k8s/k8s-dce-deploy.md
=> remove tips about 1.26 unsupported

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.13.0.md, docs/zh/docs/download/index.md
download: addon version updated to v0.13.0
=> download: addon version updated to v0.13.0

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.14.0.md, docs/zh/docs/download/index.md
download: addon version updated to v0.14.0
=> download: addon version updated to v0.14.0

docs/zh/docs/insight/intro/releasenote.md
=> update release note

docs/zh/docs/kpanda/user-guide/gpu/nvidia/install_nvidia_driver_of_operator.md
=> update nvidia dirver version

docs/zh/docs/download/business/dce5-installer-history.md, docs/zh/docs/download/business/dce5-installer-v0.15.0.md, docs/zh/docs/download/free/dce5-installer-history.md, docs/zh/docs/download/free/dce5-installer-v0.15.0.md, docs/zh/docs/download/index.md
download: dce5 version updated to v0.15.0
=> download: dce5 version updated to v0.15.0

docs/zh/docs/download/addon/history.md, docs/zh/docs/download/addon/v0.15.0.md, docs/zh/docs/download/index.md
download: addon version updated to v0.15.0
=> download: addon version updated to v0.15.0

docs/zh/docs/kpanda/user-guide/gpu/nvidia/install_nvidia_driver_of_operator.md
=> update gpu_operator docs

docs/zh/docs/native/knowledge/git/cmd.md, docs/zh/navigation.yml
=> Add instructions about git commands

docs/zh/docs/kpanda/user-guide/helm/upload-helm.md, docs/zh/navigation.yml
fix layout issues
cc @zhiyingfang2022
=> update helm/upload-helm.md for kpanda

docs/en/docs/storage/hwameistor/install/drbdinstall.md, docs/zh/docs/storage/hwameistor/install/drbdinstall.md
=> [en] update install/drbdinstall.md for hwameistor
